// Skyline Aviation — Inventory Items Mock Data (100 items across 5 locations)

import type { InventoryItem } from './types';

export const inventoryItems: InventoryItem[] = [
  // ============================================================
  // ORD MRO Hub — 30 items
  // ============================================================
  { id: 'inv-001', partNumber: 'CFM56-7B-BV-001', alternatePN: ['CFM56-7B-BV-001A'], description: 'CFM56-7B engine bleed valve assembly', category: 'Engine Parts', currentStock: 0, minimumStock: 2, reorderPoint: 3, unitCost: 95000, location: 'ORD MRO Hub', status: 'Out of Stock', lastRestocked: '2025-12-10', nextDelivery: '2026-03-24', leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-002', partNumber: '65-44892-3', alternatePN: [], description: 'Hydraulic quantity transmitter (B737)', category: 'Avionics LRUs', currentStock: 1, minimumStock: 2, reorderPoint: 3, unitCost: 12500, location: 'ORD MRO Hub', status: 'Low Stock', lastRestocked: '2026-01-15', nextDelivery: null, leadTimeDays: 10, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-003', partNumber: '820920-1', alternatePN: ['820920-2'], description: 'Pack flow control valve (B737/A320)', category: 'Rotables', currentStock: 3, minimumStock: 2, reorderPoint: 4, unitCost: 28000, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-02-20', nextDelivery: null, leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-004', partNumber: 'MLG-STRUT-737-OH', alternatePN: [], description: 'Main landing gear shock strut (B737) overhauled', category: 'Rotables', currentStock: 0, minimumStock: 1, reorderPoint: 2, unitCost: 185000, location: 'ORD MRO Hub', status: 'Out of Stock', lastRestocked: '2025-08-15', nextDelivery: '2026-04-15', leadTimeDays: 30, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-005', partNumber: 'FCC-B737-CH-B', alternatePN: [], description: 'Flight control computer channel B (B737)', category: 'Avionics LRUs', currentStock: 2, minimumStock: 2, reorderPoint: 3, unitCost: 88000, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-01-20', nextDelivery: null, leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-006', partNumber: 'HYD-FILTER-KIT-01', alternatePN: ['HYD-FILTER-KIT-01A'], description: 'Hydraulic filter elements kit (A & B systems)', category: 'Expendables', currentStock: 18, minimumStock: 10, reorderPoint: 15, unitCost: 1200, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-03-05', nextDelivery: null, leadTimeDays: 5, isRotable: false, shelfLife: '24 months', condition: 'serviceable' },
  { id: 'inv-007', partNumber: 'OIL-FILTER-CFM56', alternatePN: [], description: 'Engine oil filter kit CFM56-7B', category: 'Expendables', currentStock: 24, minimumStock: 12, reorderPoint: 18, unitCost: 850, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-02-17', nextDelivery: null, leadTimeDays: 5, isRotable: false, shelfLife: '36 months', condition: 'serviceable' },
  { id: 'inv-008', partNumber: 'TIRE-737-MAIN', alternatePN: ['TIRE-737-MAIN-R'], description: 'Main tire assembly B737 (retreaded)', category: 'Expendables', currentStock: 8, minimumStock: 8, reorderPoint: 12, unitCost: 1700, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-03-01', nextDelivery: null, leadTimeDays: 7, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-009', partNumber: 'IRU-HW-4000', alternatePN: [], description: 'Inertial Reference Unit (IRU)', category: 'Avionics LRUs', currentStock: 1, minimumStock: 2, reorderPoint: 3, unitCost: 95000, location: 'ORD MRO Hub', status: 'Low Stock', lastRestocked: '2025-11-20', nextDelivery: '2026-04-08', leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-010', partNumber: 'APU-IGN-321', alternatePN: [], description: 'APU igniter assembly (A321)', category: 'Rotables', currentStock: 4, minimumStock: 2, reorderPoint: 3, unitCost: 4200, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-03-21', nextDelivery: null, leadTimeDays: 5, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-011', partNumber: 'BRAKE-LINING-737', alternatePN: [], description: 'Main wheel brake linings set (B737)', category: 'Expendables', currentStock: 6, minimumStock: 4, reorderPoint: 8, unitCost: 8500, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-02-28', nextDelivery: null, leadTimeDays: 10, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-012', partNumber: 'NWS-DAMPER-737', alternatePN: [], description: 'Nose wheel steering damper (B737)', category: 'Rotables', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 18500, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-03-21', nextDelivery: null, leadTimeDays: 7, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-013', partNumber: 'SEAL-KIT-HYD-A', alternatePN: [], description: 'Hydraulic system seal and gasket kit', category: 'Consumables', currentStock: 15, minimumStock: 8, reorderPoint: 12, unitCost: 450, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-02-15', nextDelivery: null, leadTimeDays: 3, isRotable: false, shelfLife: '18 months', condition: 'serviceable' },
  { id: 'inv-014', partNumber: 'MIL-PRF-83282-55', alternatePN: [], description: 'Hydraulic fluid MIL-PRF-83282 (55 gal drum)', category: 'Consumables', currentStock: 4, minimumStock: 3, reorderPoint: 5, unitCost: 3200, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-03-08', nextDelivery: null, leadTimeDays: 5, isRotable: false, shelfLife: '60 months', condition: 'serviceable' },
  { id: 'inv-015', partNumber: 'O2-GEN-40PK', alternatePN: [], description: 'Oxygen generator canisters (pack of 40)', category: 'Safety Equipment', currentStock: 3, minimumStock: 2, reorderPoint: 4, unitCost: 22000, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-01-10', nextDelivery: null, leadTimeDays: 14, isRotable: false, shelfLife: '60 months', condition: 'serviceable' },
  { id: 'inv-016', partNumber: 'ELEV-FEEL-COMP', alternatePN: [], description: 'Elevator feel computer (B737)', category: 'Rotables', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 55000, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-03-14', nextDelivery: null, leadTimeDays: 10, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-017', partNumber: 'TCAS-SWR-MAX', alternatePN: [], description: 'TCAS transceiver (B737 MAX)', category: 'Avionics LRUs', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 68000, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2025-11-25', nextDelivery: null, leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-018', partNumber: 'FD-COMP-737-1', alternatePN: [], description: 'Flight Director Computer #1 (B737)', category: 'Avionics LRUs', currentStock: 0, minimumStock: 1, reorderPoint: 2, unitCost: 72000, location: 'ORD MRO Hub', status: 'Out of Stock', lastRestocked: '2025-09-01', nextDelivery: '2026-04-05', leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-019', partNumber: 'LOCKWIRE-KIT-GEN', alternatePN: [], description: 'Safety lockwire kit (assorted)', category: 'Consumables', currentStock: 30, minimumStock: 15, reorderPoint: 20, unitCost: 85, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-03-14', nextDelivery: null, leadTimeDays: 3, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-020', partNumber: 'SEALANT-PR1422', alternatePN: [], description: 'Polysulfide sealant PR-1422 (case)', category: 'Consumables', currentStock: 12, minimumStock: 6, reorderPoint: 10, unitCost: 320, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-03-10', nextDelivery: null, leadTimeDays: 5, isRotable: false, shelfLife: '12 months', condition: 'serviceable' },
  { id: 'inv-021', partNumber: 'NWS-POS-SENSOR', alternatePN: [], description: 'Nose wheel steering position sensor', category: 'Rotables', currentStock: 0, minimumStock: 1, reorderPoint: 2, unitCost: 5500, location: 'ORD MRO Hub', status: 'Out of Stock', lastRestocked: '2025-10-15', nextDelivery: '2026-03-24', leadTimeDays: 7, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-022', partNumber: 'IDG-737-OH', alternatePN: [], description: 'IDG (Integrated Drive Generator) B737 overhauled', category: 'Rotables', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 125000, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2025-12-20', nextDelivery: null, leadTimeDays: 21, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-023', partNumber: 'COTTER-PIN-AST', alternatePN: [], description: 'Cotter pin assortment kit', category: 'Consumables', currentStock: 25, minimumStock: 10, reorderPoint: 15, unitCost: 45, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-03-14', nextDelivery: null, leadTimeDays: 3, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-024', partNumber: 'HEPA-FILTER-737', alternatePN: [], description: 'Cabin air HEPA filter (B737)', category: 'Expendables', currentStock: 5, minimumStock: 4, reorderPoint: 6, unitCost: 2800, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-02-10', nextDelivery: null, leadTimeDays: 7, isRotable: false, shelfLife: '24 months', condition: 'serviceable' },
  { id: 'inv-025', partNumber: 'HYD-PUMP-SYS-A', alternatePN: [], description: 'Hydraulic pump assembly system A (B737 MAX)', category: 'Rotables', currentStock: 0, minimumStock: 1, reorderPoint: 2, unitCost: 52000, location: 'ORD MRO Hub', status: 'Out of Stock', lastRestocked: '2025-08-20', nextDelivery: '2026-04-04', leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-026', partNumber: 'MOBIL-JET-OIL-II', alternatePN: [], description: 'Engine oil Mobil Jet Oil II (case 24 qt)', category: 'Consumables', currentStock: 20, minimumStock: 10, reorderPoint: 15, unitCost: 350, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-03-07', nextDelivery: null, leadTimeDays: 3, isRotable: false, shelfLife: '48 months', condition: 'serviceable' },
  { id: 'inv-027', partNumber: 'FIRE-DET-ELEM-B', alternatePN: [], description: 'Fire detection element loop B (APU)', category: 'Safety Equipment', currentStock: 2, minimumStock: 2, reorderPoint: 3, unitCost: 4800, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-01-05', nextDelivery: null, leadTimeDays: 10, isRotable: false, shelfLife: '36 months', condition: 'serviceable' },
  { id: 'inv-028', partNumber: 'STBY-HYD-PRSW', alternatePN: [], description: 'Standby hydraulic pump pressure switch', category: 'Rotables', currentStock: 2, minimumStock: 1, reorderPoint: 2, unitCost: 3200, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-02-01', nextDelivery: null, leadTimeDays: 7, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-029', partNumber: 'DME-XCVR-002', alternatePN: ['622-8986-001'], description: 'DME transceiver #2', category: 'Avionics LRUs', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 35000, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2025-12-10', nextDelivery: null, leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-030', partNumber: 'NDT-TOOL-KIT-C', alternatePN: [], description: 'NDT inspection tooling kit (C-Check)', category: 'Tooling', currentStock: 2, minimumStock: 1, reorderPoint: 1, unitCost: 35000, location: 'ORD MRO Hub', status: 'In Stock', lastRestocked: '2026-03-14', nextDelivery: null, leadTimeDays: 10, isRotable: false, shelfLife: null, condition: 'serviceable' },

  // ============================================================
  // LAX Parts Depot — 20 items
  // ============================================================
  { id: 'inv-031', partNumber: 'FMC-A320-UNIT', alternatePN: [], description: 'Flight Management Computer (A320 family)', category: 'Avionics LRUs', currentStock: 0, minimumStock: 1, reorderPoint: 2, unitCost: 185000, location: 'LAX Parts Depot', status: 'Out of Stock', lastRestocked: '2025-10-05', nextDelivery: '2026-03-23', leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-032', partNumber: 'RADALT-XCVR-2', alternatePN: ['066-01188-0301'], description: 'Radio altimeter transceiver #2', category: 'Avionics LRUs', currentStock: 0, minimumStock: 1, reorderPoint: 2, unitCost: 42000, location: 'LAX Parts Depot', status: 'Out of Stock', lastRestocked: '2025-09-20', nextDelivery: '2026-03-24', leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-033', partNumber: 'LEAP-1A-COMB-LNR', alternatePN: [], description: 'LEAP-1A combustion chamber liner segment', category: 'Engine Parts', currentStock: 1, minimumStock: 3, reorderPoint: 5, unitCost: 145000, location: 'LAX Parts Depot', status: 'Low Stock', lastRestocked: '2025-11-10', nextDelivery: '2026-04-20', leadTimeDays: 28, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-034', partNumber: 'RECIRC-FAN-A320', alternatePN: [], description: 'Cabin recirculation fan motor (A320)', category: 'Rotables', currentStock: 2, minimumStock: 1, reorderPoint: 2, unitCost: 8500, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-02-15', nextDelivery: null, leadTimeDays: 10, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-035', partNumber: 'AT-SERVO-A320', alternatePN: [], description: 'Autothrottle servo motor (A320)', category: 'Rotables', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 35000, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-01-20', nextDelivery: null, leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-036', partNumber: 'APU-BLEED-VLV-A3', alternatePN: [], description: 'APU bleed valve assembly (A320)', category: 'Rotables', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 18000, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-02-05', nextDelivery: null, leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-037', partNumber: 'TIRE-A320-MAIN', alternatePN: [], description: 'Main tire assembly A320 (new)', category: 'Expendables', currentStock: 6, minimumStock: 4, reorderPoint: 8, unitCost: 1900, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-03-01', nextDelivery: null, leadTimeDays: 7, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-038', partNumber: 'BRAKE-LINING-A32', alternatePN: [], description: 'Main wheel brake linings set (A320)', category: 'Expendables', currentStock: 4, minimumStock: 3, reorderPoint: 6, unitCost: 9200, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-02-20', nextDelivery: null, leadTimeDays: 10, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-039', partNumber: 'WX-RADAR-PED-MTR', alternatePN: [], description: 'Weather radar antenna pedestal tilt motor', category: 'Rotables', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 22000, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-01-10', nextDelivery: null, leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-040', partNumber: 'GALLEY-COFFEE-A3', alternatePN: [], description: 'Galley coffee maker unit (A320 family)', category: 'Cabin Parts', currentStock: 3, minimumStock: 2, reorderPoint: 4, unitCost: 3500, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-03-11', nextDelivery: null, leadTimeDays: 7, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-041', partNumber: 'HEPA-FILTER-A320', alternatePN: [], description: 'Cabin air HEPA filter (A320)', category: 'Expendables', currentStock: 8, minimumStock: 4, reorderPoint: 6, unitCost: 3000, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-02-25', nextDelivery: null, leadTimeDays: 7, isRotable: false, shelfLife: '24 months', condition: 'serviceable' },
  { id: 'inv-042', partNumber: 'SPOILER-ACT-A320', alternatePN: [], description: 'Spoiler actuator assembly (A320)', category: 'Rotables', currentStock: 1, minimumStock: 2, reorderPoint: 3, unitCost: 42000, location: 'LAX Parts Depot', status: 'Low Stock', lastRestocked: '2025-12-15', nextDelivery: '2026-04-10', leadTimeDays: 18, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-043', partNumber: 'OIL-FILTER-LEAP1', alternatePN: [], description: 'Engine oil filter kit LEAP-1A', category: 'Expendables', currentStock: 12, minimumStock: 6, reorderPoint: 10, unitCost: 1100, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-03-05', nextDelivery: null, leadTimeDays: 5, isRotable: false, shelfLife: '36 months', condition: 'serviceable' },
  { id: 'inv-044', partNumber: 'SEALANT-PR1776', alternatePN: [], description: 'Fuel tank sealant PR-1776 (tube)', category: 'Consumables', currentStock: 20, minimumStock: 10, reorderPoint: 15, unitCost: 180, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-02-28', nextDelivery: null, leadTimeDays: 5, isRotable: false, shelfLife: '12 months', condition: 'serviceable' },
  { id: 'inv-045', partNumber: 'PSU-O2-MASK-MECH', alternatePN: [], description: 'PSU oxygen mask deployment mechanism', category: 'Safety Equipment', currentStock: 10, minimumStock: 5, reorderPoint: 8, unitCost: 650, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-01-20', nextDelivery: null, leadTimeDays: 7, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-046', partNumber: 'CABIN-PRESS-CTRL', alternatePN: [], description: 'Cabin pressure controller (A321)', category: 'Avionics LRUs', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 45000, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-02-10', nextDelivery: null, leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-047', partNumber: 'GALLEY-BUS-CONT', alternatePN: [], description: 'Galley bus contactor (A321)', category: 'Rotables', currentStock: 2, minimumStock: 1, reorderPoint: 2, unitCost: 3800, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-01-25', nextDelivery: null, leadTimeDays: 7, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-048', partNumber: 'APU-OIL-XDCR', alternatePN: [], description: 'APU oil pressure transducer', category: 'Rotables', currentStock: 2, minimumStock: 1, reorderPoint: 2, unitCost: 2800, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-02-20', nextDelivery: null, leadTimeDays: 7, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-049', partNumber: 'ELT-BATT-PACK', alternatePN: [], description: 'ELT battery pack', category: 'Safety Equipment', currentStock: 3, minimumStock: 2, reorderPoint: 4, unitCost: 1800, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-03-10', nextDelivery: null, leadTimeDays: 10, isRotable: false, shelfLife: '24 months', condition: 'serviceable' },
  { id: 'inv-050', partNumber: 'SEAT-TRACK-KIT', alternatePN: [], description: 'Seat track rollers and bearings set', category: 'Cabin Parts', currentStock: 5, minimumStock: 3, reorderPoint: 5, unitCost: 4500, location: 'LAX Parts Depot', status: 'In Stock', lastRestocked: '2026-03-16', nextDelivery: null, leadTimeDays: 7, isRotable: false, shelfLife: null, condition: 'serviceable' },

  // ============================================================
  // LHR Stores — 20 items
  // ============================================================
  { id: 'inv-051', partNumber: 'GCU-787-R', alternatePN: ['976J555-3'], description: 'Generator control unit right (B787)', category: 'Avionics LRUs', currentStock: 0, minimumStock: 1, reorderPoint: 2, unitCost: 65000, location: 'LHR Stores', status: 'Out of Stock', lastRestocked: '2025-10-01', nextDelivery: '2026-04-05', leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-052', partNumber: 'BMU-787-UPG', alternatePN: [], description: 'Battery monitoring unit upgraded (B787)', category: 'Avionics LRUs', currentStock: 2, minimumStock: 2, reorderPoint: 3, unitCost: 28000, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2026-03-17', nextDelivery: null, leadTimeDays: 10, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-053', partNumber: 'WX-RADAR-XCVR', alternatePN: [], description: 'Weather radar transceiver unit (B787)', category: 'Avionics LRUs', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 78000, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2025-12-05', nextDelivery: null, leadTimeDays: 21, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-054', partNumber: 'GENX-FAN-BLADE', alternatePN: [], description: 'GEnx-1B fan blade individual', category: 'Engine Parts', currentStock: 2, minimumStock: 2, reorderPoint: 4, unitCost: 180000, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2026-01-15', nextDelivery: null, leadTimeDays: 35, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-055', partNumber: 'GENX-TURB-DISC', alternatePN: [], description: 'GEnx-1B turbine disc stage 1', category: 'Engine Parts', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 650000, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2025-11-20', nextDelivery: null, leadTimeDays: 45, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-056', partNumber: 'NLG-787-ASSY', alternatePN: [], description: 'Nose landing gear assembly (B787) overhauled', category: 'Rotables', currentStock: 1, minimumStock: 1, reorderPoint: 1, unitCost: 350000, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2025-11-20', nextDelivery: null, leadTimeDays: 60, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-057', partNumber: 'TIRE-787-MAIN', alternatePN: [], description: 'Main tire assembly B787', category: 'Expendables', currentStock: 4, minimumStock: 4, reorderPoint: 6, unitCost: 3200, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2026-02-10', nextDelivery: null, leadTimeDays: 10, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-058', partNumber: 'OIL-FILTER-GENX', alternatePN: [], description: 'Engine oil filter kit GEnx-1B', category: 'Expendables', currentStock: 8, minimumStock: 4, reorderPoint: 6, unitCost: 1500, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2026-03-01', nextDelivery: null, leadTimeDays: 7, isRotable: false, shelfLife: '36 months', condition: 'serviceable' },
  { id: 'inv-059', partNumber: 'GEN-BRUSH-KIT', alternatePN: [], description: 'Generator brush replacement kit', category: 'Expendables', currentStock: 6, minimumStock: 4, reorderPoint: 6, unitCost: 2200, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2026-02-15', nextDelivery: null, leadTimeDays: 7, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-060', partNumber: 'HEPA-FILTER-787', alternatePN: [], description: 'Cabin air HEPA filter set (B787)', category: 'Expendables', currentStock: 3, minimumStock: 2, reorderPoint: 4, unitCost: 4500, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2026-02-20', nextDelivery: null, leadTimeDays: 10, isRotable: false, shelfLife: '24 months', condition: 'serviceable' },
  { id: 'inv-061', partNumber: 'LIFE-RAFT-787', alternatePN: [], description: 'Life raft assembly (B787)', category: 'Safety Equipment', currentStock: 2, minimumStock: 2, reorderPoint: 3, unitCost: 18000, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2025-12-01', nextDelivery: null, leadTimeDays: 21, isRotable: false, shelfLife: '36 months', condition: 'serviceable' },
  { id: 'inv-062', partNumber: 'MOBIL-JET-254', alternatePN: [], description: 'Engine oil Mobil Jet Oil 254 (case)', category: 'Consumables', currentStock: 10, minimumStock: 5, reorderPoint: 8, unitCost: 420, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2026-03-05', nextDelivery: null, leadTimeDays: 5, isRotable: false, shelfLife: '48 months', condition: 'serviceable' },
  { id: 'inv-063', partNumber: 'COMP-REPAIR-KIT', alternatePN: [], description: 'Composite repair kit (B787 fuselage)', category: 'Consumables', currentStock: 3, minimumStock: 2, reorderPoint: 4, unitCost: 8500, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2026-01-25', nextDelivery: null, leadTimeDays: 14, isRotable: false, shelfLife: '12 months', condition: 'serviceable' },
  { id: 'inv-064', partNumber: 'BUS-TIE-RELAY', alternatePN: [], description: 'AC bus tie relay (B777)', category: 'Rotables', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 8500, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2026-02-01', nextDelivery: null, leadTimeDays: 10, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-065', partNumber: 'TRIM-AIR-VALVE', alternatePN: [], description: 'Trim air modulating valve (B777)', category: 'Rotables', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 8200, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2026-01-10', nextDelivery: null, leadTimeDays: 10, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-066', partNumber: 'BRAKE-TEMP-SNSR', alternatePN: [], description: 'Brake temperature sensor (B737)', category: 'Rotables', currentStock: 2, minimumStock: 2, reorderPoint: 3, unitCost: 3500, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2026-02-10', nextDelivery: null, leadTimeDays: 7, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-067', partNumber: 'IFE-SERVER-787', alternatePN: [], description: 'IFE server unit (B787)', category: 'Avionics LRUs', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 32000, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2026-01-20', nextDelivery: null, leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-068', partNumber: 'CABIN-FILTER-777', alternatePN: [], description: 'Cabin air HEPA filter set (B777)', category: 'Expendables', currentStock: 2, minimumStock: 2, reorderPoint: 3, unitCost: 5200, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2026-03-08', nextDelivery: null, leadTimeDays: 10, isRotable: false, shelfLife: '24 months', condition: 'serviceable' },
  { id: 'inv-069', partNumber: 'SEAL-KIT-GENX', alternatePN: [], description: 'GEnx engine seal and gasket kit', category: 'Consumables', currentStock: 4, minimumStock: 2, reorderPoint: 4, unitCost: 2800, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2026-02-15', nextDelivery: null, leadTimeDays: 10, isRotable: false, shelfLife: '18 months', condition: 'serviceable' },
  { id: 'inv-070', partNumber: 'GPS-RCVR-787-2', alternatePN: ['066-04032-0201'], description: 'GPS receiver unit #2 (B787)', category: 'Avionics LRUs', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 48000, location: 'LHR Stores', status: 'In Stock', lastRestocked: '2025-12-20', nextDelivery: null, leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },

  // ============================================================
  // SIN MRO Center — 15 items
  // ============================================================
  { id: 'inv-071', partNumber: 'GE90-HPT-BLADE', alternatePN: [], description: 'GE90-115B HPT stage 1 blade set', category: 'Engine Parts', currentStock: 0, minimumStock: 1, reorderPoint: 1, unitCost: 850000, location: 'SIN MRO Center', status: 'On Order', lastRestocked: '2025-06-15', nextDelivery: '2026-03-28', leadTimeDays: 42, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-072', partNumber: 'GE90-COMB-LINER', alternatePN: [], description: 'GE90-115B combustion liner panels', category: 'Engine Parts', currentStock: 1, minimumStock: 2, reorderPoint: 3, unitCost: 320000, location: 'SIN MRO Center', status: 'Low Stock', lastRestocked: '2025-09-10', nextDelivery: '2026-04-05', leadTimeDays: 45, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-073', partNumber: 'GE90-NGV-SET', alternatePN: [], description: 'GE90-115B HPT nozzle guide vane set', category: 'Engine Parts', currentStock: 0, minimumStock: 1, reorderPoint: 1, unitCost: 420000, location: 'SIN MRO Center', status: 'On Order', lastRestocked: '2025-07-20', nextDelivery: '2026-03-28', leadTimeDays: 35, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-074', partNumber: 'TRENT-XWB-FAN', alternatePN: [], description: 'Trent XWB fan blade individual', category: 'Engine Parts', currentStock: 2, minimumStock: 2, reorderPoint: 3, unitCost: 280000, location: 'SIN MRO Center', status: 'In Stock', lastRestocked: '2026-01-10', nextDelivery: null, leadTimeDays: 35, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-075', partNumber: 'MLG-777-STRUT', alternatePN: [], description: 'Main landing gear strut (B777) overhauled', category: 'Rotables', currentStock: 1, minimumStock: 1, reorderPoint: 1, unitCost: 480000, location: 'SIN MRO Center', status: 'In Stock', lastRestocked: '2025-11-15', nextDelivery: null, leadTimeDays: 60, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-076', partNumber: 'TIRE-777-MAIN', alternatePN: [], description: 'Main tire assembly B777', category: 'Expendables', currentStock: 4, minimumStock: 4, reorderPoint: 6, unitCost: 4500, location: 'SIN MRO Center', status: 'In Stock', lastRestocked: '2026-02-15', nextDelivery: null, leadTimeDays: 14, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-077', partNumber: 'OIL-FILTER-GE90', alternatePN: [], description: 'Engine oil filter kit GE90-115B', category: 'Expendables', currentStock: 6, minimumStock: 4, reorderPoint: 6, unitCost: 1800, location: 'SIN MRO Center', status: 'In Stock', lastRestocked: '2026-03-01', nextDelivery: null, leadTimeDays: 7, isRotable: false, shelfLife: '36 months', condition: 'serviceable' },
  { id: 'inv-078', partNumber: 'OIL-FILTER-TXWB', alternatePN: [], description: 'Engine oil filter kit Trent XWB', category: 'Expendables', currentStock: 4, minimumStock: 3, reorderPoint: 5, unitCost: 1600, location: 'SIN MRO Center', status: 'In Stock', lastRestocked: '2026-02-20', nextDelivery: null, leadTimeDays: 7, isRotable: false, shelfLife: '36 months', condition: 'serviceable' },
  { id: 'inv-079', partNumber: 'LIFE-VEST-PAX', alternatePN: [], description: 'Passenger life vest (pack of 50)', category: 'Safety Equipment', currentStock: 8, minimumStock: 4, reorderPoint: 6, unitCost: 1500, location: 'SIN MRO Center', status: 'In Stock', lastRestocked: '2026-01-20', nextDelivery: null, leadTimeDays: 14, isRotable: false, shelfLife: '60 months', condition: 'serviceable' },
  { id: 'inv-080', partNumber: 'HEPA-FILTER-350', alternatePN: [], description: 'Cabin air HEPA filter set (A350)', category: 'Expendables', currentStock: 3, minimumStock: 2, reorderPoint: 4, unitCost: 4800, location: 'SIN MRO Center', status: 'In Stock', lastRestocked: '2026-03-05', nextDelivery: null, leadTimeDays: 10, isRotable: false, shelfLife: '24 months', condition: 'serviceable' },
  { id: 'inv-081', partNumber: 'CARGO-SMOKE-DET', alternatePN: [], description: 'Cargo compartment smoke detector assembly', category: 'Safety Equipment', currentStock: 2, minimumStock: 2, reorderPoint: 3, unitCost: 12000, location: 'SIN MRO Center', status: 'In Stock', lastRestocked: '2026-02-10', nextDelivery: null, leadTimeDays: 10, isRotable: false, shelfLife: '36 months', condition: 'serviceable' },
  { id: 'inv-082', partNumber: 'SEAL-KIT-GE90', alternatePN: [], description: 'GE90 engine seal kit (hot section)', category: 'Consumables', currentStock: 3, minimumStock: 2, reorderPoint: 3, unitCost: 15000, location: 'SIN MRO Center', status: 'In Stock', lastRestocked: '2026-02-01', nextDelivery: null, leadTimeDays: 14, isRotable: false, shelfLife: '18 months', condition: 'serviceable' },
  { id: 'inv-083', partNumber: 'BORE-SCOPE-KIT', alternatePN: [], description: 'Engine borescope inspection kit (GE90/Trent)', category: 'Tooling', currentStock: 2, minimumStock: 1, reorderPoint: 1, unitCost: 45000, location: 'SIN MRO Center', status: 'In Stock', lastRestocked: '2025-12-10', nextDelivery: null, leadTimeDays: 21, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-084', partNumber: 'IFE-SCREEN-350', alternatePN: [], description: 'IFE seatback screen assembly (A350)', category: 'Cabin Parts', currentStock: 10, minimumStock: 5, reorderPoint: 8, unitCost: 1200, location: 'SIN MRO Center', status: 'In Stock', lastRestocked: '2026-02-15', nextDelivery: null, leadTimeDays: 14, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-085', partNumber: 'LIFE-RAFT-350', alternatePN: [], description: 'Life raft assembly (A350)', category: 'Safety Equipment', currentStock: 2, minimumStock: 2, reorderPoint: 3, unitCost: 20000, location: 'SIN MRO Center', status: 'In Stock', lastRestocked: '2025-11-25', nextDelivery: null, leadTimeDays: 21, isRotable: false, shelfLife: '36 months', condition: 'serviceable' },

  // ============================================================
  // DFW Warehouse — 15 items
  // ============================================================
  { id: 'inv-086', partNumber: 'LEAP-1A-FAN-BLD', alternatePN: [], description: 'LEAP-1A fan blade individual', category: 'Engine Parts', currentStock: 2, minimumStock: 2, reorderPoint: 4, unitCost: 120000, location: 'DFW Warehouse', status: 'In Stock', lastRestocked: '2026-01-20', nextDelivery: null, leadTimeDays: 28, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-087', partNumber: 'LEAP-1B-FAN-BLD', alternatePN: [], description: 'LEAP-1B fan blade individual', category: 'Engine Parts', currentStock: 1, minimumStock: 2, reorderPoint: 3, unitCost: 115000, location: 'DFW Warehouse', status: 'Low Stock', lastRestocked: '2025-12-05', nextDelivery: null, leadTimeDays: 28, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-088', partNumber: 'MLG-A320-STRUT', alternatePN: [], description: 'Main landing gear strut (A320) overhauled', category: 'Rotables', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 195000, location: 'DFW Warehouse', status: 'In Stock', lastRestocked: '2026-02-01', nextDelivery: null, leadTimeDays: 30, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-089', partNumber: 'HYD-PUMP-A320-B', alternatePN: [], description: 'Hydraulic pump system B (A320)', category: 'Rotables', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 48000, location: 'DFW Warehouse', status: 'In Stock', lastRestocked: '2026-01-15', nextDelivery: null, leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-090', partNumber: 'TIRE-A321-MAIN', alternatePN: [], description: 'Main tire assembly A321 (new)', category: 'Expendables', currentStock: 4, minimumStock: 4, reorderPoint: 6, unitCost: 2100, location: 'DFW Warehouse', status: 'In Stock', lastRestocked: '2026-03-10', nextDelivery: null, leadTimeDays: 7, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-091', partNumber: 'BRAKE-A321-SET', alternatePN: [], description: 'Main wheel brake assembly set (A321)', category: 'Expendables', currentStock: 2, minimumStock: 2, reorderPoint: 4, unitCost: 11000, location: 'DFW Warehouse', status: 'In Stock', lastRestocked: '2026-02-25', nextDelivery: null, leadTimeDays: 10, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-092', partNumber: 'LEAP-1A-OIL-FLT', alternatePN: [], description: 'Engine oil filter kit LEAP-1A (DFW stock)', category: 'Expendables', currentStock: 10, minimumStock: 6, reorderPoint: 8, unitCost: 1100, location: 'DFW Warehouse', status: 'In Stock', lastRestocked: '2026-03-01', nextDelivery: null, leadTimeDays: 5, isRotable: false, shelfLife: '36 months', condition: 'serviceable' },
  { id: 'inv-093', partNumber: 'HYD-FLUID-55G', alternatePN: [], description: 'Hydraulic fluid Skydrol LD-4 (55 gal)', category: 'Consumables', currentStock: 3, minimumStock: 2, reorderPoint: 4, unitCost: 4200, location: 'DFW Warehouse', status: 'In Stock', lastRestocked: '2026-02-15', nextDelivery: null, leadTimeDays: 7, isRotable: false, shelfLife: '60 months', condition: 'serviceable' },
  { id: 'inv-094', partNumber: 'LEAP-1A-BORE-TL', alternatePN: [], description: 'LEAP-1A borescope inspection tooling', category: 'Tooling', currentStock: 1, minimumStock: 1, reorderPoint: 1, unitCost: 25000, location: 'DFW Warehouse', status: 'In Stock', lastRestocked: '2026-01-10', nextDelivery: null, leadTimeDays: 14, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-095', partNumber: 'RUDDER-PCU-SEAL', alternatePN: [], description: 'Rudder PCU seal kit (B737)', category: 'Expendables', currentStock: 3, minimumStock: 2, reorderPoint: 4, unitCost: 4500, location: 'DFW Warehouse', status: 'In Stock', lastRestocked: '2026-02-20', nextDelivery: null, leadTimeDays: 7, isRotable: false, shelfLife: '18 months', condition: 'serviceable' },
  { id: 'inv-096', partNumber: 'WINDSHIELD-MAX', alternatePN: [], description: 'Windshield assembly (B737 MAX) captain side', category: 'Rotables', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 42000, location: 'DFW Warehouse', status: 'In Stock', lastRestocked: '2025-12-15', nextDelivery: null, leadTimeDays: 21, isRotable: true, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-097', partNumber: 'LEAP-1B-OIL-FLT', alternatePN: [], description: 'Engine oil filter kit LEAP-1B', category: 'Expendables', currentStock: 8, minimumStock: 4, reorderPoint: 6, unitCost: 1050, location: 'DFW Warehouse', status: 'In Stock', lastRestocked: '2026-03-05', nextDelivery: null, leadTimeDays: 5, isRotable: false, shelfLife: '36 months', condition: 'serviceable' },
  { id: 'inv-098', partNumber: 'HEPA-FILTER-321', alternatePN: [], description: 'Cabin air HEPA filter set (A321)', category: 'Expendables', currentStock: 4, minimumStock: 3, reorderPoint: 5, unitCost: 3200, location: 'DFW Warehouse', status: 'In Stock', lastRestocked: '2026-02-28', nextDelivery: null, leadTimeDays: 7, isRotable: false, shelfLife: '24 months', condition: 'serviceable' },
  { id: 'inv-099', partNumber: 'LAV-EXHAUST-FAN', alternatePN: [], description: 'Lavatory exhaust fan motor assembly', category: 'Cabin Parts', currentStock: 3, minimumStock: 2, reorderPoint: 3, unitCost: 2800, location: 'DFW Warehouse', status: 'In Stock', lastRestocked: '2026-02-10', nextDelivery: null, leadTimeDays: 10, isRotable: false, shelfLife: null, condition: 'serviceable' },
  { id: 'inv-100', partNumber: 'HYD-PRESS-REG', alternatePN: [], description: 'Hydraulic pump pressure regulator (B737 MAX)', category: 'Rotables', currentStock: 1, minimumStock: 1, reorderPoint: 2, unitCost: 15000, location: 'DFW Warehouse', status: 'Low Stock', lastRestocked: '2025-11-05', nextDelivery: null, leadTimeDays: 14, isRotable: true, shelfLife: null, condition: 'serviceable' },
];
