// Skyline Aviation — Maintenance Records Mock Data (70 records)

import type { MaintenanceRecord } from './types';

export const maintenanceRecords: MaintenanceRecord[] = [
  // ============================================================
  // OVERDUE (10) — Critical, High, Medium priorities
  // ============================================================
  {
    id: 'mx-001',
    aircraftId: 'ac-005',
    tailNumber: 'N73805',
    checkType: 'Engine Shop Visit',
    trigger: 'condition',
    category: 'Engines',
    description: 'Left engine bleed valve failure — AOG at ORD. Engine requires removal and shop visit for bleed air system overhaul.',
    status: 'Overdue',
    priority: 'Critical',
    scheduledDate: '2026-03-15',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 4500000,
    actualCost: null,
    downtimeHours: 336,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'GE Aviation Spares',
    adReference: null,
    sbReference: 'SB-CFM56-72-0948',
    linkedProcurementIds: ['pr-041', 'pr-042'],
  },
  {
    id: 'mx-002',
    aircraftId: 'ac-015',
    tailNumber: 'N320A3',
    checkType: 'AD Compliance',
    trigger: 'ad_mandate',
    category: 'Avionics',
    description: 'Flight Management Computer failure — AOG at LAX. FMC unit unserviceable, requires replacement and recertification.',
    status: 'Overdue',
    priority: 'Critical',
    scheduledDate: '2026-03-18',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 380000,
    actualCost: null,
    downtimeHours: 168,
    mroFacility: 'LAX MRO Center',
    vendor: 'Honeywell Aerospace',
    adReference: 'AD-2026-04-12',
    sbReference: null,
    linkedProcurementIds: ['pr-043', 'pr-044'],
  },
  {
    id: 'mx-003',
    aircraftId: 'ac-013',
    tailNumber: 'N320A1',
    checkType: 'Engine Shop Visit',
    trigger: 'condition',
    category: 'Engines',
    description: 'CFM LEAP-1A combustion chamber hot section inspection — elevated EGT trend detected. Unscheduled borescope reveals combustion liner cracking.',
    status: 'Overdue',
    priority: 'High',
    scheduledDate: '2026-03-10',
    completedDate: null,
    hoursRemaining: 120,
    cyclesRemaining: 80,
    costEstimate: 3200000,
    actualCost: null,
    downtimeHours: 240,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Safran Parts',
    adReference: null,
    sbReference: 'SB-LEAP-1A-72-0234',
    linkedProcurementIds: ['pr-045'],
  },
  {
    id: 'mx-004',
    aircraftId: 'ac-017',
    tailNumber: 'N320A5',
    checkType: 'Service Bulletin',
    trigger: 'condition',
    category: 'Engines',
    description: 'CFM LEAP-1A combustion chamber inspection — fleet-wide SB compliance. Similar EGT anomaly pattern as N320A1.',
    status: 'Overdue',
    priority: 'High',
    scheduledDate: '2026-03-12',
    completedDate: null,
    hoursRemaining: 200,
    cyclesRemaining: 150,
    costEstimate: 2800000,
    actualCost: null,
    downtimeHours: 200,
    mroFacility: 'DFW Heavy Maintenance',
    vendor: 'Safran Parts',
    adReference: null,
    sbReference: 'SB-LEAP-1A-72-0234',
    linkedProcurementIds: ['pr-046'],
  },
  {
    id: 'mx-005',
    aircraftId: 'ac-027',
    tailNumber: 'N77701',
    checkType: 'C-Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'C-Check overdue by 8 days. Full structural inspection, corrosion prevention, and systems check required.',
    status: 'Overdue',
    priority: 'High',
    scheduledDate: '2026-03-15',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 2800000,
    actualCost: null,
    downtimeHours: 720,
    mroFacility: 'SIN MRO Hub',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-006',
    aircraftId: 'ac-001',
    tailNumber: 'N73801',
    checkType: 'Landing Gear Overhaul',
    trigger: 'cycles',
    category: 'Landing Gear',
    description: 'Main landing gear overhaul overdue. Cycle limit exceeded by 240 cycles. Requires overhaul at next ground opportunity.',
    status: 'Overdue',
    priority: 'Medium',
    scheduledDate: '2026-03-05',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: -240,
    costEstimate: 850000,
    actualCost: null,
    downtimeHours: 168,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Heico Corp',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: ['pr-047'],
  },
  {
    id: 'mx-007',
    aircraftId: 'ac-003',
    tailNumber: 'N73803',
    checkType: 'AD Compliance',
    trigger: 'ad_mandate',
    category: 'Flight Controls',
    description: 'Rudder PCU seal inspection per AD-2026-02-08. Overdue by 5 days.',
    status: 'Overdue',
    priority: 'Medium',
    scheduledDate: '2026-03-18',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 45000,
    actualCost: null,
    downtimeHours: 24,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Boeing Distribution',
    adReference: 'AD-2026-02-08',
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-008',
    aircraftId: 'ac-010',
    tailNumber: 'N38M02',
    checkType: 'Line Check',
    trigger: 'flight_hours',
    category: 'Hydraulics',
    description: 'Hydraulic system A pressure fluctuation. Line check to inspect hydraulic pump and relief valves.',
    status: 'Overdue',
    priority: 'Medium',
    scheduledDate: '2026-03-20',
    completedDate: null,
    hoursRemaining: 50,
    cyclesRemaining: null,
    costEstimate: 12000,
    actualCost: null,
    downtimeHours: 8,
    mroFacility: 'DFW Heavy Maintenance',
    vendor: 'Honeywell Aerospace',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-009',
    aircraftId: 'ac-019',
    tailNumber: 'N321A1',
    checkType: 'Service Bulletin',
    trigger: 'condition',
    category: 'Pressurization',
    description: 'Cabin pressure controller software update per SB. Minor pressurization oscillation reported by flight crew.',
    status: 'Overdue',
    priority: 'Medium',
    scheduledDate: '2026-03-17',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 18000,
    actualCost: null,
    downtimeHours: 12,
    mroFacility: 'LAX MRO Center',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: 'SB-A321-21-1045',
    linkedProcurementIds: [],
  },
  {
    id: 'mx-010',
    aircraftId: 'ac-023',
    tailNumber: 'N78901',
    checkType: 'Line Check',
    trigger: 'flight_hours',
    category: 'Electrical',
    description: 'Generator control unit intermittent fault. Requires inspection and potential GCU replacement.',
    status: 'Overdue',
    priority: 'Medium',
    scheduledDate: '2026-03-19',
    completedDate: null,
    hoursRemaining: 80,
    cyclesRemaining: null,
    costEstimate: 25000,
    actualCost: null,
    downtimeHours: 16,
    mroFacility: 'LHR Line Maintenance',
    vendor: 'Honeywell Aerospace',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },

  // ============================================================
  // SCHEDULED (15) — next 90 days
  // ============================================================
  {
    id: 'mx-011',
    aircraftId: 'ac-004',
    tailNumber: 'N73804',
    checkType: 'A-Check',
    trigger: 'flight_hours',
    category: 'Airframe',
    description: 'Scheduled A-Check. Full systems inspection, fluid servicing, and component replacements per MPD.',
    status: 'Scheduled',
    priority: 'Medium',
    scheduledDate: '2026-04-20',
    completedDate: null,
    hoursRemaining: 500,
    cyclesRemaining: 400,
    costEstimate: 120000,
    actualCost: null,
    downtimeHours: 48,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-012',
    aircraftId: 'ac-009',
    tailNumber: 'N38M01',
    checkType: 'A-Check',
    trigger: 'flight_hours',
    category: 'Airframe',
    description: 'First A-Check for N38M01. Systems inspection and lubrication per Boeing MPD.',
    status: 'Scheduled',
    priority: 'Low',
    scheduledDate: '2026-05-15',
    completedDate: null,
    hoursRemaining: 800,
    cyclesRemaining: 640,
    costEstimate: 95000,
    actualCost: null,
    downtimeHours: 36,
    mroFacility: 'DFW Heavy Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-013',
    aircraftId: 'ac-013',
    tailNumber: 'N320A1',
    checkType: 'A-Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'Scheduled A-Check per Airbus maintenance planning document.',
    status: 'Scheduled',
    priority: 'Medium',
    scheduledDate: '2026-06-10',
    completedDate: null,
    hoursRemaining: 1200,
    cyclesRemaining: 960,
    costEstimate: 110000,
    actualCost: null,
    downtimeHours: 48,
    mroFacility: 'LAX MRO Center',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-014',
    aircraftId: 'ac-015',
    tailNumber: 'N320A3',
    checkType: 'Engine Shop Visit',
    trigger: 'condition',
    category: 'Engines',
    description: 'CFM LEAP-1A combustion chamber — third A320neo with similar pattern. Scheduled post-AOG recovery for full engine shop visit.',
    status: 'Scheduled',
    priority: 'High',
    scheduledDate: '2026-04-15',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 5200000,
    actualCost: null,
    downtimeHours: 480,
    mroFacility: 'LAX MRO Center',
    vendor: 'Safran Parts',
    adReference: null,
    sbReference: 'SB-LEAP-1A-72-0234',
    linkedProcurementIds: ['pr-048'],
  },
  {
    id: 'mx-015',
    aircraftId: 'ac-023',
    tailNumber: 'N78901',
    checkType: 'A-Check',
    trigger: 'flight_hours',
    category: 'Airframe',
    description: 'B787-9 A-Check. Composite structure inspection, systems check, and component replacements.',
    status: 'Scheduled',
    priority: 'Medium',
    scheduledDate: '2026-05-01',
    completedDate: null,
    hoursRemaining: 600,
    cyclesRemaining: 300,
    costEstimate: 180000,
    actualCost: null,
    downtimeHours: 72,
    mroFacility: 'LHR Line Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-016',
    aircraftId: 'ac-027',
    tailNumber: 'N77701',
    checkType: 'C-Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'Full C-Check. Structural inspection, NDT testing, corrosion treatment, and systems overhaul.',
    status: 'Scheduled',
    priority: 'High',
    scheduledDate: '2026-04-05',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 2500000,
    actualCost: null,
    downtimeHours: 720,
    mroFacility: 'SIN MRO Hub',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-017',
    aircraftId: 'ac-029',
    tailNumber: 'N35001',
    checkType: 'A-Check',
    trigger: 'flight_hours',
    category: 'Airframe',
    description: 'A350-900 A-Check. Composite airframe inspection and Trent XWB engine trend monitoring.',
    status: 'Scheduled',
    priority: 'Low',
    scheduledDate: '2026-05-20',
    completedDate: null,
    hoursRemaining: 900,
    cyclesRemaining: 450,
    costEstimate: 175000,
    actualCost: null,
    downtimeHours: 60,
    mroFacility: 'SIN MRO Hub',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-018',
    aircraftId: 'ac-006',
    tailNumber: 'N73806',
    checkType: 'Line Check',
    trigger: 'flight_hours',
    category: 'APU',
    description: 'APU performance check. Elevated oil consumption trend requires inspection.',
    status: 'Scheduled',
    priority: 'Low',
    scheduledDate: '2026-04-10',
    completedDate: null,
    hoursRemaining: 300,
    cyclesRemaining: null,
    costEstimate: 8500,
    actualCost: null,
    downtimeHours: 6,
    mroFacility: 'LAX MRO Center',
    vendor: 'Honeywell Aerospace',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-019',
    aircraftId: 'ac-014',
    tailNumber: 'N320A2',
    checkType: 'AD Compliance',
    trigger: 'ad_mandate',
    category: 'Flight Controls',
    description: 'Spoiler actuator inspection per Airbus AD. All A320neo fleet affected.',
    status: 'Scheduled',
    priority: 'Medium',
    scheduledDate: '2026-04-25',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 35000,
    actualCost: null,
    downtimeHours: 16,
    mroFacility: 'DFW Heavy Maintenance',
    vendor: 'Airbus Spares',
    adReference: 'AD-2026-03-15',
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-020',
    aircraftId: 'ac-024',
    tailNumber: 'N78902',
    checkType: 'Service Bulletin',
    trigger: 'condition',
    category: 'Avionics',
    description: 'Weather radar software update per Boeing SB. Enhanced turbulence detection capability.',
    status: 'Scheduled',
    priority: 'Low',
    scheduledDate: '2026-05-05',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 22000,
    actualCost: null,
    downtimeHours: 8,
    mroFacility: 'LHR Line Maintenance',
    vendor: 'Honeywell Aerospace',
    adReference: null,
    sbReference: 'SB-787-34-0127',
    linkedProcurementIds: [],
  },
  {
    id: 'mx-021',
    aircraftId: 'ac-020',
    tailNumber: 'N321A2',
    checkType: 'Line Check',
    trigger: 'flight_hours',
    category: 'Hydraulics',
    description: 'Hydraulic fluid sampling and filter replacement. Routine maintenance.',
    status: 'Scheduled',
    priority: 'Low',
    scheduledDate: '2026-04-30',
    completedDate: null,
    hoursRemaining: 400,
    cyclesRemaining: null,
    costEstimate: 5500,
    actualCost: null,
    downtimeHours: 4,
    mroFacility: 'LAX MRO Center',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-022',
    aircraftId: 'ac-016',
    tailNumber: 'N320A4',
    checkType: 'AD Compliance',
    trigger: 'ad_mandate',
    category: 'Engines',
    description: 'LEAP-1A fan blade inspection per AD-2026-01-22. Mandatory inspection at next shop visit or 500 cycles.',
    status: 'Scheduled',
    priority: 'Medium',
    scheduledDate: '2026-05-10',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: 500,
    costEstimate: 65000,
    actualCost: null,
    downtimeHours: 24,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Safran Parts',
    adReference: 'AD-2026-01-22',
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-023',
    aircraftId: 'ac-030',
    tailNumber: 'N35002',
    checkType: 'Line Check',
    trigger: 'flight_hours',
    category: 'Interiors',
    description: 'Cabin interior inspection and seat track repair. Multiple seat mechanisms reported stiff.',
    status: 'Scheduled',
    priority: 'Low',
    scheduledDate: '2026-04-18',
    completedDate: null,
    hoursRemaining: 350,
    cyclesRemaining: null,
    costEstimate: 15000,
    actualCost: null,
    downtimeHours: 10,
    mroFacility: 'SIN MRO Hub',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-024',
    aircraftId: 'ac-011',
    tailNumber: 'N38M03',
    checkType: 'Line Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'Routine 90-day line check. Visual inspection, fluid levels, and tire condition.',
    status: 'Scheduled',
    priority: 'Low',
    scheduledDate: '2026-05-12',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 7500,
    actualCost: null,
    downtimeHours: 4,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-025',
    aircraftId: 'ac-022',
    tailNumber: 'N321A4',
    checkType: 'A-Check',
    trigger: 'flight_hours',
    category: 'Airframe',
    description: 'A321neo first A-Check. Full MPD task card execution.',
    status: 'Scheduled',
    priority: 'Medium',
    scheduledDate: '2026-06-01',
    completedDate: null,
    hoursRemaining: 1000,
    cyclesRemaining: 800,
    costEstimate: 105000,
    actualCost: null,
    downtimeHours: 48,
    mroFacility: 'DFW Heavy Maintenance',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },

  // ============================================================
  // IN PROGRESS (10)
  // ============================================================
  {
    id: 'mx-026',
    aircraftId: 'ac-008',
    tailNumber: 'N73808',
    checkType: 'C-Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'C-Check in progress at DFW Heavy Maintenance. Structural NDT inspection phase.',
    status: 'In Progress',
    priority: 'High',
    scheduledDate: '2026-03-20',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 1800000,
    actualCost: null,
    downtimeHours: 480,
    mroFacility: 'DFW Heavy Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: ['pr-049'],
  },
  {
    id: 'mx-027',
    aircraftId: 'ac-021',
    tailNumber: 'N321A3',
    checkType: 'B-Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'B-Check in progress at ORD. Airframe systems and component inspection phase.',
    status: 'In Progress',
    priority: 'Medium',
    scheduledDate: '2026-03-25',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 350000,
    actualCost: null,
    downtimeHours: 96,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-028',
    aircraftId: 'ac-028',
    tailNumber: 'N77702',
    checkType: 'Engine Shop Visit',
    trigger: 'flight_hours',
    category: 'Engines',
    description: 'GE90-115B engine shop visit at SIN MRO Hub. Hot section inspection and HPT blade replacement.',
    status: 'In Progress',
    priority: 'High',
    scheduledDate: '2026-03-20',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 7500000,
    actualCost: null,
    downtimeHours: 720,
    mroFacility: 'SIN MRO Hub',
    vendor: 'GE Aviation Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: ['pr-050'],
  },
  {
    id: 'mx-029',
    aircraftId: 'ac-005',
    tailNumber: 'N73805',
    checkType: 'Line Check',
    trigger: 'condition',
    category: 'Engines',
    description: 'Emergency bleed valve troubleshooting in progress. Awaiting replacement valve from AOG procurement.',
    status: 'In Progress',
    priority: 'Critical',
    scheduledDate: '2026-03-22',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 85000,
    actualCost: null,
    downtimeHours: 48,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'GE Aviation Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: ['pr-041'],
  },
  {
    id: 'mx-030',
    aircraftId: 'ac-015',
    tailNumber: 'N320A3',
    checkType: 'Line Check',
    trigger: 'condition',
    category: 'Avionics',
    description: 'FMC replacement in progress. New unit received, software loading and verification underway.',
    status: 'In Progress',
    priority: 'Critical',
    scheduledDate: '2026-03-22',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 45000,
    actualCost: null,
    downtimeHours: 24,
    mroFacility: 'LAX MRO Center',
    vendor: 'Honeywell Aerospace',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: ['pr-043'],
  },
  {
    id: 'mx-031',
    aircraftId: 'ac-002',
    tailNumber: 'N73802',
    checkType: 'AD Compliance',
    trigger: 'ad_mandate',
    category: 'Flight Controls',
    description: 'Elevator feel computer modification per AD. Software update and bench test in progress.',
    status: 'In Progress',
    priority: 'Medium',
    scheduledDate: '2026-03-21',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 32000,
    actualCost: null,
    downtimeHours: 12,
    mroFacility: 'DFW Heavy Maintenance',
    vendor: 'Boeing Distribution',
    adReference: 'AD-2026-01-30',
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-032',
    aircraftId: 'ac-026',
    tailNumber: 'N78904',
    checkType: 'Service Bulletin',
    trigger: 'condition',
    category: 'Electrical',
    description: 'Battery monitoring system upgrade per Boeing SB. Enhanced thermal runaway detection.',
    status: 'In Progress',
    priority: 'Medium',
    scheduledDate: '2026-03-22',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 55000,
    actualCost: null,
    downtimeHours: 16,
    mroFacility: 'LHR Line Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: 'SB-787-24-0089',
    linkedProcurementIds: [],
  },
  {
    id: 'mx-033',
    aircraftId: 'ac-007',
    tailNumber: 'N73807',
    checkType: 'Line Check',
    trigger: 'condition',
    category: 'Landing Gear',
    description: 'Nose wheel steering shimmy investigation. Damper replacement underway.',
    status: 'In Progress',
    priority: 'Medium',
    scheduledDate: '2026-03-23',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 18000,
    actualCost: null,
    downtimeHours: 8,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Heico Corp',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-034',
    aircraftId: 'ac-019',
    tailNumber: 'N321A1',
    checkType: 'Line Check',
    trigger: 'condition',
    category: 'APU',
    description: 'APU igniter replacement. Slow start observed during last 3 ground operations.',
    status: 'In Progress',
    priority: 'Low',
    scheduledDate: '2026-03-23',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 6500,
    actualCost: null,
    downtimeHours: 4,
    mroFacility: 'LAX MRO Center',
    vendor: 'Honeywell Aerospace',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-035',
    aircraftId: 'ac-012',
    tailNumber: 'N38M04',
    checkType: 'Line Check',
    trigger: 'condition',
    category: 'Avionics',
    description: 'IRS alignment issue troubleshooting. Intermittent drift on IRU #2.',
    status: 'In Progress',
    priority: 'Medium',
    scheduledDate: '2026-03-23',
    completedDate: null,
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 42000,
    actualCost: null,
    downtimeHours: 12,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Honeywell Aerospace',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },

  // ============================================================
  // COMPLETED (35) — last 6 months
  // ============================================================
  {
    id: 'mx-036',
    aircraftId: 'ac-001',
    tailNumber: 'N73801',
    checkType: 'A-Check',
    trigger: 'flight_hours',
    category: 'Airframe',
    description: 'Scheduled A-Check completed. All task cards signed off.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2025-11-10',
    completedDate: '2025-11-12',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 115000,
    actualCost: 122500,
    downtimeHours: 48,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-037',
    aircraftId: 'ac-002',
    tailNumber: 'N73802',
    checkType: 'Line Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'Routine 90-day line check completed.',
    status: 'Completed',
    priority: 'Low',
    scheduledDate: '2025-12-05',
    completedDate: '2025-12-05',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 7000,
    actualCost: 6800,
    downtimeHours: 4,
    mroFacility: 'DFW Heavy Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-038',
    aircraftId: 'ac-003',
    tailNumber: 'N73803',
    checkType: 'A-Check',
    trigger: 'flight_hours',
    category: 'Airframe',
    description: 'A-Check with additional corrosion treatment on wing root fairing.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2026-01-15',
    completedDate: '2026-01-17',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 120000,
    actualCost: 145000,
    downtimeHours: 56,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-039',
    aircraftId: 'ac-004',
    tailNumber: 'N73804',
    checkType: 'Line Check',
    trigger: 'calendar',
    category: 'Engines',
    description: 'Engine oil sampling and analysis. Results within normal parameters.',
    status: 'Completed',
    priority: 'Low',
    scheduledDate: '2025-10-20',
    completedDate: '2025-10-20',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 3000,
    actualCost: 2800,
    downtimeHours: 2,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'GE Aviation Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-040',
    aircraftId: 'ac-006',
    tailNumber: 'N73806',
    checkType: 'A-Check',
    trigger: 'flight_hours',
    category: 'Airframe',
    description: 'Scheduled A-Check. Additional brake assembly replacement included.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2026-02-20',
    completedDate: '2026-02-22',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 110000,
    actualCost: 128000,
    downtimeHours: 52,
    mroFacility: 'LAX MRO Center',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-041',
    aircraftId: 'ac-007',
    tailNumber: 'N73807',
    checkType: 'A-Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'A-Check completed. All items signed off with no findings.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2026-01-05',
    completedDate: '2026-01-07',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 100000,
    actualCost: 98500,
    downtimeHours: 44,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-042',
    aircraftId: 'ac-009',
    tailNumber: 'N38M01',
    checkType: 'Line Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: '90-day line check. Clean bill of health.',
    status: 'Completed',
    priority: 'Low',
    scheduledDate: '2026-02-01',
    completedDate: '2026-02-01',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 6500,
    actualCost: 6200,
    downtimeHours: 4,
    mroFacility: 'DFW Heavy Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-043',
    aircraftId: 'ac-010',
    tailNumber: 'N38M02',
    checkType: 'Line Check',
    trigger: 'flight_hours',
    category: 'Landing Gear',
    description: 'Tire replacement and brake wear measurement. Two main tires replaced.',
    status: 'Completed',
    priority: 'Low',
    scheduledDate: '2026-01-18',
    completedDate: '2026-01-18',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 12000,
    actualCost: 14500,
    downtimeHours: 6,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Heico Corp',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-044',
    aircraftId: 'ac-011',
    tailNumber: 'N38M03',
    checkType: 'Line Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'Routine line check completed on schedule.',
    status: 'Completed',
    priority: 'Low',
    scheduledDate: '2026-02-12',
    completedDate: '2026-02-12',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 6000,
    actualCost: 5800,
    downtimeHours: 3,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-045',
    aircraftId: 'ac-012',
    tailNumber: 'N38M04',
    checkType: 'Line Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'Line check with additional windshield inspection. Minor crazing noted, within limits.',
    status: 'Completed',
    priority: 'Low',
    scheduledDate: '2026-03-01',
    completedDate: '2026-03-01',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 7000,
    actualCost: 7200,
    downtimeHours: 4,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-046',
    aircraftId: 'ac-014',
    tailNumber: 'N320A2',
    checkType: 'A-Check',
    trigger: 'flight_hours',
    category: 'Airframe',
    description: 'A-Check completed with no significant findings.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2026-01-25',
    completedDate: '2026-01-27',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 105000,
    actualCost: 102000,
    downtimeHours: 44,
    mroFacility: 'LAX MRO Center',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-047',
    aircraftId: 'ac-016',
    tailNumber: 'N320A4',
    checkType: 'Line Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: '90-day line check. Completed on schedule.',
    status: 'Completed',
    priority: 'Low',
    scheduledDate: '2026-02-15',
    completedDate: '2026-02-15',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 6500,
    actualCost: 6300,
    downtimeHours: 4,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-048',
    aircraftId: 'ac-017',
    tailNumber: 'N320A5',
    checkType: 'A-Check',
    trigger: 'flight_hours',
    category: 'Airframe',
    description: 'A-Check completed. Additional cabin pressure controller check performed.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2026-01-08',
    completedDate: '2026-01-10',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 100000,
    actualCost: 108000,
    downtimeHours: 48,
    mroFacility: 'DFW Heavy Maintenance',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-049',
    aircraftId: 'ac-018',
    tailNumber: 'N320A6',
    checkType: 'Line Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'Routine line check. Minor cabin defects rectified.',
    status: 'Completed',
    priority: 'Low',
    scheduledDate: '2026-03-10',
    completedDate: '2026-03-10',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 8000,
    actualCost: 9200,
    downtimeHours: 5,
    mroFacility: 'DFW Heavy Maintenance',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-050',
    aircraftId: 'ac-019',
    tailNumber: 'N321A1',
    checkType: 'A-Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'A-Check with additional engine borescope. No findings.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2025-12-20',
    completedDate: '2025-12-22',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 115000,
    actualCost: 118000,
    downtimeHours: 50,
    mroFacility: 'LAX MRO Center',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-051',
    aircraftId: 'ac-020',
    tailNumber: 'N321A2',
    checkType: 'Line Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'Line check completed. Oxygen bottle pressure check included.',
    status: 'Completed',
    priority: 'Low',
    scheduledDate: '2026-02-05',
    completedDate: '2026-02-05',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 7500,
    actualCost: 7200,
    downtimeHours: 4,
    mroFacility: 'LAX MRO Center',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-052',
    aircraftId: 'ac-022',
    tailNumber: 'N321A4',
    checkType: 'Line Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'Routine line check. All items satisfactory.',
    status: 'Completed',
    priority: 'Low',
    scheduledDate: '2026-02-28',
    completedDate: '2026-02-28',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 6500,
    actualCost: 6400,
    downtimeHours: 3,
    mroFacility: 'DFW Heavy Maintenance',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-053',
    aircraftId: 'ac-023',
    tailNumber: 'N78901',
    checkType: 'Line Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'Transit check at LHR. All items serviceable.',
    status: 'Completed',
    priority: 'Low',
    scheduledDate: '2025-11-01',
    completedDate: '2025-11-01',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 8000,
    actualCost: 7500,
    downtimeHours: 4,
    mroFacility: 'LHR Line Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-054',
    aircraftId: 'ac-024',
    tailNumber: 'N78902',
    checkType: 'A-Check',
    trigger: 'flight_hours',
    category: 'Airframe',
    description: 'A-Check with composite structure detailed inspection. No delamination found.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2026-01-10',
    completedDate: '2026-01-13',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 170000,
    actualCost: 165000,
    downtimeHours: 72,
    mroFacility: 'LHR Line Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-055',
    aircraftId: 'ac-025',
    tailNumber: 'N78903',
    checkType: 'Line Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'Routine line check at LHR. Minor galley equipment repair.',
    status: 'Completed',
    priority: 'Low',
    scheduledDate: '2026-02-20',
    completedDate: '2026-02-20',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 9000,
    actualCost: 11500,
    downtimeHours: 6,
    mroFacility: 'LHR Line Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-056',
    aircraftId: 'ac-026',
    tailNumber: 'N78904',
    checkType: 'Line Check',
    trigger: 'calendar',
    category: 'Electrical',
    description: 'Electrical system check. Generator brush replacement performed.',
    status: 'Completed',
    priority: 'Low',
    scheduledDate: '2025-12-15',
    completedDate: '2025-12-15',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 15000,
    actualCost: 18000,
    downtimeHours: 8,
    mroFacility: 'SIN MRO Hub',
    vendor: 'Honeywell Aerospace',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-057',
    aircraftId: 'ac-027',
    tailNumber: 'N77701',
    checkType: 'A-Check',
    trigger: 'flight_hours',
    category: 'Airframe',
    description: 'A-Check at SIN with additional landing gear inspection.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2025-10-05',
    completedDate: '2025-10-08',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 200000,
    actualCost: 215000,
    downtimeHours: 72,
    mroFacility: 'SIN MRO Hub',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-058',
    aircraftId: 'ac-028',
    tailNumber: 'N77702',
    checkType: 'A-Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'A-Check completed prior to engine shop visit.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2025-07-20',
    completedDate: '2025-07-23',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 195000,
    actualCost: 192000,
    downtimeHours: 68,
    mroFacility: 'SIN MRO Hub',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-059',
    aircraftId: 'ac-029',
    tailNumber: 'N35001',
    checkType: 'Line Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'Line check at SIN. IFE system update included.',
    status: 'Completed',
    priority: 'Low',
    scheduledDate: '2026-01-20',
    completedDate: '2026-01-20',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 10000,
    actualCost: 12500,
    downtimeHours: 6,
    mroFacility: 'SIN MRO Hub',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-060',
    aircraftId: 'ac-030',
    tailNumber: 'N35002',
    checkType: 'A-Check',
    trigger: 'flight_hours',
    category: 'Airframe',
    description: 'A-Check. Trent XWB engine trend review within parameters.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2026-03-05',
    completedDate: '2026-03-07',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 160000,
    actualCost: 155000,
    downtimeHours: 56,
    mroFacility: 'SIN MRO Hub',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-061',
    aircraftId: 'ac-005',
    tailNumber: 'N73805',
    checkType: 'A-Check',
    trigger: 'flight_hours',
    category: 'Airframe',
    description: 'Last A-Check before AOG event. Completed normally.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2025-09-15',
    completedDate: '2025-09-17',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 130000,
    actualCost: 135000,
    downtimeHours: 52,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-062',
    aircraftId: 'ac-015',
    tailNumber: 'N320A3',
    checkType: 'A-Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'Last A-Check. FMC was functioning normally at that time.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2025-11-20',
    completedDate: '2025-11-22',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 105000,
    actualCost: 110000,
    downtimeHours: 48,
    mroFacility: 'LAX MRO Center',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-063',
    aircraftId: 'ac-008',
    tailNumber: 'N73808',
    checkType: 'A-Check',
    trigger: 'flight_hours',
    category: 'Airframe',
    description: 'A-Check prior to scheduled C-Check.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2025-08-12',
    completedDate: '2025-08-14',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 105000,
    actualCost: 100000,
    downtimeHours: 44,
    mroFacility: 'DFW Heavy Maintenance',
    vendor: 'Boeing Distribution',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-064',
    aircraftId: 'ac-013',
    tailNumber: 'N320A1',
    checkType: 'Line Check',
    trigger: 'condition',
    category: 'Engines',
    description: 'Initial LEAP-1A EGT trend investigation. Borescope inspection revealed early signs of combustion liner wear.',
    status: 'Completed',
    priority: 'High',
    scheduledDate: '2025-12-10',
    completedDate: '2025-12-12',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 25000,
    actualCost: 28000,
    downtimeHours: 16,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Safran Parts',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-065',
    aircraftId: 'ac-021',
    tailNumber: 'N321A3',
    checkType: 'A-Check',
    trigger: 'calendar',
    category: 'Airframe',
    description: 'A-Check completed before B-Check scheduling.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2025-10-30',
    completedDate: '2025-11-01',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 110000,
    actualCost: 112000,
    downtimeHours: 48,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Airbus Spares',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-066',
    aircraftId: 'ac-004',
    tailNumber: 'N73804',
    checkType: 'AD Compliance',
    trigger: 'ad_mandate',
    category: 'Engines',
    description: 'CFM56-7B fuel nozzle inspection per AD. All nozzles within specification.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2025-10-20',
    completedDate: '2025-10-21',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 35000,
    actualCost: 32000,
    downtimeHours: 12,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'GE Aviation Spares',
    adReference: 'AD-2025-08-15',
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-067',
    aircraftId: 'ac-017',
    tailNumber: 'N320A5',
    checkType: 'Line Check',
    trigger: 'condition',
    category: 'Engines',
    description: 'LEAP-1A EGT trend check following fleet alert from N320A1 findings. Early wear pattern confirmed.',
    status: 'Completed',
    priority: 'High',
    scheduledDate: '2026-01-08',
    completedDate: '2026-01-10',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 25000,
    actualCost: 30000,
    downtimeHours: 18,
    mroFacility: 'DFW Heavy Maintenance',
    vendor: 'Safran Parts',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-068',
    aircraftId: 'ac-025',
    tailNumber: 'N78903',
    checkType: 'AD Compliance',
    trigger: 'ad_mandate',
    category: 'Engines',
    description: 'GEnx-1B turbine disc inspection per AD. Completed with no findings.',
    status: 'Completed',
    priority: 'High',
    scheduledDate: '2025-12-01',
    completedDate: '2025-12-03',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 85000,
    actualCost: 82000,
    downtimeHours: 48,
    mroFacility: 'LHR Line Maintenance',
    vendor: 'GE Aviation Spares',
    adReference: 'AD-2025-10-22',
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-069',
    aircraftId: 'ac-024',
    tailNumber: 'N78902',
    checkType: 'Landing Gear Overhaul',
    trigger: 'cycles',
    category: 'Landing Gear',
    description: 'Nose landing gear overhaul. Strut reseal and steering collar replacement.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2025-11-15',
    completedDate: '2025-11-20',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 420000,
    actualCost: 445000,
    downtimeHours: 120,
    mroFacility: 'LHR Line Maintenance',
    vendor: 'Heico Corp',
    adReference: null,
    sbReference: null,
    linkedProcurementIds: [],
  },
  {
    id: 'mx-070',
    aircraftId: 'ac-010',
    tailNumber: 'N38M02',
    checkType: 'Service Bulletin',
    trigger: 'condition',
    category: 'Avionics',
    description: 'TCAS software update per Boeing SB. Enhanced resolution advisory logic.',
    status: 'Completed',
    priority: 'Medium',
    scheduledDate: '2025-11-25',
    completedDate: '2025-11-25',
    hoursRemaining: null,
    cyclesRemaining: null,
    costEstimate: 18000,
    actualCost: 17500,
    downtimeHours: 6,
    mroFacility: 'ORD Line Maintenance',
    vendor: 'Honeywell Aerospace',
    adReference: null,
    sbReference: 'SB-737MAX-34-0056',
    linkedProcurementIds: [],
  },
];
