// SkyStratos Aviation — MEL (Minimum Equipment List) Items Mock Data (25 items)
// "Today" = 2026-03-23

import type { MELItem } from './types';

export const melItems: MELItem[] = [
  // ============================================================
  // Category A — 4 items (fix within 1-3 days per MEL)
  // ============================================================
  {
    id: 'mel-001',
    aircraftId: 'ac-005',
    tailNumber: 'N73805',
    ataChapter: '29',
    description: 'Hydraulic system B quantity indication failed. System pressure normal, gauge inoperative.',
    category: 'A',
    deferredDate: '2026-03-21',
    expiryDate: '2026-03-24',
    dispatchConditions: 'Hydraulic quantity must be verified manually before each flight. Maintenance must check fluid level.',
    rectificationAction: 'Replace hydraulic quantity transmitter P/N 65-44892-3.',
    status: 'active',
  },
  {
    id: 'mel-002',
    aircraftId: 'ac-005',
    tailNumber: 'N73805',
    ataChapter: '26',
    description: 'APU fire detection loop B inoperative. Loop A operational.',
    category: 'A',
    deferredDate: '2026-03-22',
    expiryDate: '2026-03-25',
    dispatchConditions: 'APU fire detection loop A must be verified operational before each dispatch.',
    rectificationAction: 'Replace fire detection element loop B, test per AMM 26-22-00.',
    status: 'active',
  },
  {
    id: 'mel-003',
    aircraftId: 'ac-015',
    tailNumber: 'N320A3',
    ataChapter: '34',
    description: 'Radio altimeter #2 inoperative. #1 system operational.',
    category: 'A',
    deferredDate: '2026-03-22',
    expiryDate: '2026-03-25',
    dispatchConditions: 'Autoland capability not available. CAT II/III approaches prohibited. Radio altimeter #1 must be verified.',
    rectificationAction: 'Replace radio altimeter transceiver #2 P/N 066-01188-0301.',
    status: 'active',
  },
  {
    id: 'mel-004',
    aircraftId: 'ac-027',
    tailNumber: 'N77701',
    ataChapter: '24',
    description: 'Standby AC bus tie relay intermittent. Main bus ties normal.',
    category: 'A',
    deferredDate: '2026-03-21',
    expiryDate: '2026-03-23',
    dispatchConditions: 'Standby power system verified before each dispatch. MEL operational check required.',
    rectificationAction: 'Replace bus tie relay assembly and test per AMM 24-21-00.',
    status: 'active',
  },

  // ============================================================
  // Category B — 8 items (3 calendar days), 2 approaching expiry
  // ============================================================
  {
    id: 'mel-005',
    aircraftId: 'ac-005',
    tailNumber: 'N73805',
    ataChapter: '21',
    description: 'Pack 2 flow control valve slow to respond. Pack operates but with delayed modulation.',
    category: 'B',
    deferredDate: '2026-03-21',
    expiryDate: '2026-03-24',
    dispatchConditions: 'Pack 1 must be fully operational. Passenger load limited to 85% capacity.',
    rectificationAction: 'Replace pack flow control valve P/N 820920-1.',
    status: 'active',
  },
  {
    id: 'mel-006',
    aircraftId: 'ac-003',
    tailNumber: 'N73803',
    ataChapter: '32',
    description: 'Nose wheel steering indication amber on ground. Steering functional.',
    category: 'B',
    deferredDate: '2026-03-21',
    expiryDate: '2026-03-24',
    dispatchConditions: 'Steering verified functional before each taxi. Tiller operation confirmed.',
    rectificationAction: 'Replace nose wheel steering position sensor and recalibrate.',
    status: 'active',
  },
  {
    id: 'mel-007',
    aircraftId: 'ac-013',
    tailNumber: 'N320A1',
    ataChapter: '22',
    description: 'Autothrottle disconnect on engagement above FL350. Manual throttle control normal.',
    category: 'B',
    deferredDate: '2026-03-22',
    expiryDate: '2026-03-25',
    dispatchConditions: 'Autothrottle use prohibited above FL350. Crew must manage thrust manually at cruise.',
    rectificationAction: 'Replace autothrottle servo motor and recalibrate TMS.',
    status: 'active',
  },
  {
    id: 'mel-008',
    aircraftId: 'ac-015',
    tailNumber: 'N320A3',
    ataChapter: '49',
    description: 'APU bleed air output reduced. Ground air conditioning capability degraded.',
    category: 'B',
    deferredDate: '2026-03-20',
    expiryDate: '2026-03-23',
    dispatchConditions: 'Ground power unit required for cabin conditioning during extended ground operations. APU bleed not to be used for engine start.',
    rectificationAction: 'APU compressor section inspection and bleed valve replacement.',
    status: 'active',
  },
  {
    id: 'mel-009',
    aircraftId: 'ac-019',
    tailNumber: 'N321A1',
    ataChapter: '34',
    description: 'Weather radar tilt mechanism sluggish. Manual tilt functional with effort.',
    category: 'B',
    deferredDate: '2026-03-20',
    expiryDate: '2026-03-23',
    dispatchConditions: 'Weather radar available but auto-tilt inoperative. Manual tilt must be used. Avoid known severe weather areas.',
    rectificationAction: 'Replace radar antenna pedestal tilt motor assembly.',
    status: 'active',
  },
  {
    id: 'mel-010',
    aircraftId: 'ac-010',
    tailNumber: 'N38M02',
    ataChapter: '29',
    description: 'Hydraulic system A pressure fluctuating 2800-3100 PSI. Within dispatch limits but anomalous.',
    category: 'B',
    deferredDate: '2026-03-22',
    expiryDate: '2026-03-25',
    dispatchConditions: 'Monitor system A pressure. If fluctuation exceeds 500 PSI range, return to base.',
    rectificationAction: 'Replace hydraulic pump pressure regulator assembly.',
    status: 'active',
  },
  {
    id: 'mel-011',
    aircraftId: 'ac-027',
    tailNumber: 'N77701',
    ataChapter: '21',
    description: 'Zone 3 trim air valve failed closed. Zone temperature controlled by pack output only.',
    category: 'B',
    deferredDate: '2026-03-22',
    expiryDate: '2026-03-25',
    dispatchConditions: 'Business class zone temperature may deviate +/- 3 degrees from selected. Crew to inform passengers.',
    rectificationAction: 'Replace zone 3 trim air modulating valve and duct check valve.',
    status: 'active',
  },
  {
    id: 'mel-012',
    aircraftId: 'ac-023',
    tailNumber: 'N78901',
    ataChapter: '24',
    description: 'Right generator control unit intermittent BITE fault. Generator output normal.',
    category: 'B',
    deferredDate: '2026-03-22',
    expiryDate: '2026-03-25',
    dispatchConditions: 'Both generators must be confirmed operational before dispatch. Monitor EICAS for GCU faults in flight.',
    rectificationAction: 'Replace right engine generator control unit P/N 976J555-3.',
    status: 'active',
  },

  // ============================================================
  // Category C — 8 items (10 calendar days)
  // ============================================================
  {
    id: 'mel-013',
    aircraftId: 'ac-003',
    tailNumber: 'N73803',
    ataChapter: '22',
    description: 'FD pitch bar intermittent drop-out on Captain side. FO instruments normal.',
    category: 'C',
    deferredDate: '2026-03-18',
    expiryDate: '2026-03-28',
    dispatchConditions: 'Captain FD use restricted. FO to fly FD-referenced approaches. Two-pilot operation required.',
    rectificationAction: 'Replace FD computer #1 and verify EFIS display drive.',
    status: 'active',
  },
  {
    id: 'mel-014',
    aircraftId: 'ac-007',
    tailNumber: 'N73807',
    ataChapter: '32',
    description: 'Left main gear brake temperature indication intermittent. Brakes functional.',
    category: 'C',
    deferredDate: '2026-03-15',
    expiryDate: '2026-03-25',
    dispatchConditions: 'Crew to allow minimum 30-minute brake cooling before departure after landing. Visual brake inspection required.',
    rectificationAction: 'Replace brake temperature sensor and wiring harness LH main gear.',
    status: 'active',
  },
  {
    id: 'mel-015',
    aircraftId: 'ac-015',
    tailNumber: 'N320A3',
    ataChapter: '21',
    description: 'Recirculation fan #2 inoperative. #1 fan and packs normal.',
    category: 'C',
    deferredDate: '2026-03-16',
    expiryDate: '2026-03-26',
    dispatchConditions: 'Cabin air quality adequate with one recirc fan. No passenger load restriction.',
    rectificationAction: 'Replace cabin recirculation fan motor #2.',
    status: 'active',
  },
  {
    id: 'mel-016',
    aircraftId: 'ac-017',
    tailNumber: 'N320A5',
    ataChapter: '49',
    description: 'APU oil pressure indication fluctuating in green band. APU operational.',
    category: 'C',
    deferredDate: '2026-03-17',
    expiryDate: '2026-03-27',
    dispatchConditions: 'APU available for dispatch. Monitor oil pressure trend. If indication enters amber, deactivate APU.',
    rectificationAction: 'Replace APU oil pressure transducer and verify signal path.',
    status: 'active',
  },
  {
    id: 'mel-017',
    aircraftId: 'ac-014',
    tailNumber: 'N320A2',
    ataChapter: '34',
    description: 'GPS receiver #2 degraded accuracy. Position drift up to 0.1 NM noted.',
    category: 'C',
    deferredDate: '2026-03-19',
    expiryDate: '2026-03-29',
    dispatchConditions: 'GPS #1 primary. RNAV approaches require GPS #1 confirmation. DME/DME backup available.',
    rectificationAction: 'Replace GPS receiver unit #2 P/N 066-04032-0201.',
    status: 'active',
  },
  {
    id: 'mel-018',
    aircraftId: 'ac-030',
    tailNumber: 'N35002',
    ataChapter: '26',
    description: 'Cargo compartment smoke detector zone 4 self-test failure. Adjacent zones operational.',
    category: 'C',
    deferredDate: '2026-03-20',
    expiryDate: '2026-03-30',
    dispatchConditions: 'Adjacent zone smoke detectors provide coverage. Maximum cargo compartment loading restriction per MEL.',
    rectificationAction: 'Replace cargo smoke detector zone 4 and verify loop integrity.',
    status: 'active',
  },
  {
    id: 'mel-019',
    aircraftId: 'ac-001',
    tailNumber: 'N73801',
    ataChapter: '29',
    description: 'Standby hydraulic pump low-pressure light illuminates momentarily on ground. Pressure recovers.',
    category: 'C',
    deferredDate: '2026-03-20',
    expiryDate: '2026-03-30',
    dispatchConditions: 'Standby hydraulic system verified operational. Monitor for in-flight activation.',
    rectificationAction: 'Replace standby hydraulic pump pressure switch and test.',
    status: 'active',
  },
  {
    id: 'mel-020',
    aircraftId: 'ac-004',
    tailNumber: 'N73804',
    ataChapter: '22',
    description: 'Autopilot altitude capture overshoots by 100-200 ft before correcting. VNAV capture normal.',
    category: 'C',
    deferredDate: '2026-03-21',
    expiryDate: '2026-03-31',
    dispatchConditions: 'Crew to anticipate overshoot and advise ATC if necessary. Manual altitude capture recommended in congested airspace.',
    rectificationAction: 'Replace flight control computer channel B and recalibrate autopilot gains.',
    status: 'active',
  },

  // ============================================================
  // Category D — 5 items (120 calendar days)
  // ============================================================
  {
    id: 'mel-021',
    aircraftId: 'ac-005',
    tailNumber: 'N73805',
    ataChapter: '34',
    description: 'DME #2 interrogator intermittent. DME #1 and GPS position fully operational.',
    category: 'D',
    deferredDate: '2025-12-15',
    expiryDate: '2026-04-14',
    dispatchConditions: 'DME #1 required operational. GPS primary navigation. No RNAV restriction.',
    rectificationAction: 'Replace DME transceiver #2 P/N 622-8986-001.',
    status: 'active',
  },
  {
    id: 'mel-022',
    aircraftId: 'ac-019',
    tailNumber: 'N321A1',
    ataChapter: '24',
    description: 'Galley bus 2 intermittent trip. Galley 2 ovens affected. Other galleys normal.',
    category: 'D',
    deferredDate: '2026-01-05',
    expiryDate: '2026-05-05',
    dispatchConditions: 'Galley 2 ovens deactivated. Catering adjusted to use galleys 1, 3, 4. No service impact on short-haul.',
    rectificationAction: 'Replace galley bus 2 contactor and inspect wiring for chafing.',
    status: 'active',
  },
  {
    id: 'mel-023',
    aircraftId: 'ac-009',
    tailNumber: 'N38M01',
    ataChapter: '21',
    description: 'Lavatory 3 exhaust fan inoperative. Adjacent lavatory ventilation provides partial airflow.',
    category: 'D',
    deferredDate: '2026-02-10',
    expiryDate: '2026-06-10',
    dispatchConditions: 'Lavatory 3 remains available. Cabin crew to monitor. No passenger restriction.',
    rectificationAction: 'Replace lavatory exhaust fan motor and check duct connection.',
    status: 'active',
  },
  {
    id: 'mel-024',
    aircraftId: 'ac-016',
    tailNumber: 'N320A4',
    ataChapter: '34',
    description: 'ELT battery approaching expiry. ELT functional but battery due for replacement.',
    category: 'D',
    deferredDate: '2026-01-20',
    expiryDate: '2026-05-20',
    dispatchConditions: 'ELT operational. Battery replacement scheduled at next A-Check.',
    rectificationAction: 'Replace ELT battery pack per STC documentation.',
    status: 'active',
  },
  {
    id: 'mel-025',
    aircraftId: 'ac-020',
    tailNumber: 'N321A2',
    ataChapter: '26',
    description: 'Passenger oxygen mask in row 22A deployment mechanism stiff. Manual release available.',
    category: 'D',
    deferredDate: '2026-02-20',
    expiryDate: '2026-06-20',
    dispatchConditions: 'Manual release verified functional. Seat 22A occupant briefed by cabin crew on manual deployment.',
    rectificationAction: 'Replace PSU oxygen mask deployment mechanism row 22A.',
    status: 'active',
  },
];
