// SkyStratos Aviation — Procurement Records Mock Data (50 records)

import type { ProcurementRecord } from './types';

export const procurementRecords: ProcurementRecord[] = [
  // ============================================================
  // PLANNED ORDERS (35) — various statuses
  // ============================================================
  {
    id: 'pr-001',
    aircraftId: 'ac-008',
    tailNumber: 'N73808',
    category: 'Expendables',
    item: 'Main wheel brake assembly linings set',
    quantity: 4,
    unitPrice: 8500,
    totalCost: 34000,
    status: 'Delivered',
    orderDate: '2026-02-15',
    expectedDelivery: '2026-03-01',
    actualDelivery: '2026-02-28',
    supplier: 'Heico Corp',
    isEmergency: false,
    leadTime: 14,
    premiumPct: 0,
  },
  {
    id: 'pr-002',
    aircraftId: 'ac-008',
    tailNumber: 'N73808',
    category: 'Rotables',
    item: 'IDG (Integrated Drive Generator) overhauled',
    quantity: 1,
    unitPrice: 125000,
    totalCost: 125000,
    status: 'Shipped',
    orderDate: '2026-02-20',
    expectedDelivery: '2026-03-25',
    actualDelivery: null,
    supplier: 'Honeywell Aerospace',
    isEmergency: false,
    leadTime: 21,
    premiumPct: 0,
  },
  {
    id: 'pr-003',
    aircraftId: 'ac-021',
    tailNumber: 'N321A3',
    category: 'Expendables',
    item: 'Hydraulic filter elements kit (A & B systems)',
    quantity: 6,
    unitPrice: 1200,
    totalCost: 7200,
    status: 'Delivered',
    orderDate: '2026-03-01',
    expectedDelivery: '2026-03-10',
    actualDelivery: '2026-03-09',
    supplier: 'Airbus Spares',
    isEmergency: false,
    leadTime: 7,
    premiumPct: 0,
  },
  {
    id: 'pr-004',
    aircraftId: 'ac-028',
    tailNumber: 'N77702',
    category: 'Engine Parts',
    item: 'GE90-115B HPT stage 1 blade set',
    quantity: 1,
    unitPrice: 850000,
    totalCost: 850000,
    status: 'Shipped',
    orderDate: '2026-02-01',
    expectedDelivery: '2026-03-28',
    actualDelivery: null,
    supplier: 'GE Aviation Spares',
    isEmergency: false,
    leadTime: 42,
    premiumPct: 0,
  },
  {
    id: 'pr-005',
    aircraftId: 'ac-028',
    tailNumber: 'N77702',
    category: 'Engine Parts',
    item: 'GE90-115B combustion liner panels',
    quantity: 2,
    unitPrice: 320000,
    totalCost: 640000,
    status: 'Ordered',
    orderDate: '2026-02-10',
    expectedDelivery: '2026-04-05',
    actualDelivery: null,
    supplier: 'GE Aviation Spares',
    isEmergency: false,
    leadTime: 45,
    premiumPct: 0,
  },
  {
    id: 'pr-006',
    aircraftId: 'ac-001',
    tailNumber: 'N73801',
    category: 'Rotables',
    item: 'Main landing gear shock strut assembly overhauled',
    quantity: 2,
    unitPrice: 185000,
    totalCost: 370000,
    status: 'Ordered',
    orderDate: '2026-03-05',
    expectedDelivery: '2026-04-15',
    actualDelivery: null,
    supplier: 'Heico Corp',
    isEmergency: false,
    leadTime: 30,
    premiumPct: 0,
  },
  {
    id: 'pr-007',
    aircraftId: 'ac-027',
    tailNumber: 'N77701',
    category: 'Expendables',
    item: 'Cabin air HEPA filter set (full aircraft)',
    quantity: 1,
    unitPrice: 15000,
    totalCost: 15000,
    status: 'Delivered',
    orderDate: '2026-02-25',
    expectedDelivery: '2026-03-10',
    actualDelivery: '2026-03-08',
    supplier: 'Boeing Distribution',
    isEmergency: false,
    leadTime: 10,
    premiumPct: 0,
  },
  {
    id: 'pr-008',
    aircraftId: 'ac-014',
    tailNumber: 'N320A2',
    category: 'Rotables',
    item: 'Spoiler actuator assembly',
    quantity: 2,
    unitPrice: 42000,
    totalCost: 84000,
    status: 'Ordered',
    orderDate: '2026-03-15',
    expectedDelivery: '2026-04-10',
    actualDelivery: null,
    supplier: 'Airbus Spares',
    isEmergency: false,
    leadTime: 18,
    premiumPct: 0,
  },
  {
    id: 'pr-009',
    aircraftId: 'ac-029',
    tailNumber: 'N35001',
    category: 'Engine Parts',
    item: 'Trent XWB fan blade individual replacement',
    quantity: 1,
    unitPrice: 280000,
    totalCost: 280000,
    status: 'Pending Approval',
    orderDate: '2026-03-18',
    expectedDelivery: '2026-05-01',
    actualDelivery: null,
    supplier: 'Safran Parts',
    isEmergency: false,
    leadTime: 35,
    premiumPct: 0,
  },
  {
    id: 'pr-010',
    aircraftId: 'ac-023',
    tailNumber: 'N78901',
    category: 'Avionics LRUs',
    item: 'Generator Control Unit replacement',
    quantity: 1,
    unitPrice: 65000,
    totalCost: 65000,
    status: 'Ordered',
    orderDate: '2026-03-20',
    expectedDelivery: '2026-04-05',
    actualDelivery: null,
    supplier: 'Honeywell Aerospace',
    isEmergency: false,
    leadTime: 14,
    premiumPct: 0,
  },
  {
    id: 'pr-011',
    aircraftId: 'ac-004',
    tailNumber: 'N73804',
    category: 'Expendables',
    item: 'Engine oil filter kit CFM56-7B',
    quantity: 4,
    unitPrice: 850,
    totalCost: 3400,
    status: 'Delivered',
    orderDate: '2026-02-10',
    expectedDelivery: '2026-02-18',
    actualDelivery: '2026-02-17',
    supplier: 'Aviall Services',
    isEmergency: false,
    leadTime: 5,
    premiumPct: 0,
  },
  {
    id: 'pr-012',
    aircraftId: 'ac-016',
    tailNumber: 'N320A4',
    category: 'Consumables',
    item: 'Oxygen generator canisters (set of 40)',
    quantity: 1,
    unitPrice: 22000,
    totalCost: 22000,
    status: 'Shipped',
    orderDate: '2026-03-05',
    expectedDelivery: '2026-03-26',
    actualDelivery: null,
    supplier: 'Aviall Services',
    isEmergency: false,
    leadTime: 14,
    premiumPct: 0,
  },
  {
    id: 'pr-013',
    aircraftId: 'ac-024',
    tailNumber: 'N78902',
    category: 'Avionics LRUs',
    item: 'Weather radar transceiver unit',
    quantity: 1,
    unitPrice: 78000,
    totalCost: 78000,
    status: 'Pending Approval',
    orderDate: '2026-03-20',
    expectedDelivery: '2026-04-15',
    actualDelivery: null,
    supplier: 'Honeywell Aerospace',
    isEmergency: false,
    leadTime: 21,
    premiumPct: 0,
  },
  {
    id: 'pr-014',
    aircraftId: 'ac-002',
    tailNumber: 'N73802',
    category: 'Rotables',
    item: 'Elevator feel computer modified unit',
    quantity: 1,
    unitPrice: 55000,
    totalCost: 55000,
    status: 'Delivered',
    orderDate: '2026-03-01',
    expectedDelivery: '2026-03-15',
    actualDelivery: '2026-03-14',
    supplier: 'Boeing Distribution',
    isEmergency: false,
    leadTime: 10,
    premiumPct: 0,
  },
  {
    id: 'pr-015',
    aircraftId: 'ac-026',
    tailNumber: 'N78904',
    category: 'Avionics LRUs',
    item: 'Battery monitoring unit (BMU) upgraded',
    quantity: 2,
    unitPrice: 28000,
    totalCost: 56000,
    status: 'Delivered',
    orderDate: '2026-03-05',
    expectedDelivery: '2026-03-18',
    actualDelivery: '2026-03-17',
    supplier: 'Boeing Distribution',
    isEmergency: false,
    leadTime: 10,
    premiumPct: 0,
  },
  {
    id: 'pr-016',
    aircraftId: 'ac-030',
    tailNumber: 'N35002',
    category: 'Expendables',
    item: 'Seat track rollers and bearings set (20 rows)',
    quantity: 1,
    unitPrice: 4500,
    totalCost: 4500,
    status: 'Delivered',
    orderDate: '2026-03-08',
    expectedDelivery: '2026-03-18',
    actualDelivery: '2026-03-16',
    supplier: 'Airbus Spares',
    isEmergency: false,
    leadTime: 7,
    premiumPct: 0,
  },
  {
    id: 'pr-017',
    aircraftId: 'ac-013',
    tailNumber: 'N320A1',
    category: 'Engine Parts',
    item: 'LEAP-1A combustion liner segment',
    quantity: 3,
    unitPrice: 145000,
    totalCost: 435000,
    status: 'Ordered',
    orderDate: '2026-03-12',
    expectedDelivery: '2026-04-20',
    actualDelivery: null,
    supplier: 'Safran Parts',
    isEmergency: false,
    leadTime: 28,
    premiumPct: 0,
  },
  {
    id: 'pr-018',
    aircraftId: 'ac-017',
    tailNumber: 'N320A5',
    category: 'Engine Parts',
    item: 'LEAP-1A combustion liner segment',
    quantity: 2,
    unitPrice: 145000,
    totalCost: 290000,
    status: 'Ordered',
    orderDate: '2026-03-14',
    expectedDelivery: '2026-04-22',
    actualDelivery: null,
    supplier: 'Safran Parts',
    isEmergency: false,
    leadTime: 28,
    premiumPct: 0,
  },
  {
    id: 'pr-019',
    aircraftId: 'ac-009',
    tailNumber: 'N38M01',
    category: 'Cabin Parts',
    item: 'Lavatory exhaust fan motor assembly',
    quantity: 1,
    unitPrice: 2800,
    totalCost: 2800,
    status: 'Shipped',
    orderDate: '2026-03-10',
    expectedDelivery: '2026-03-24',
    actualDelivery: null,
    supplier: 'Boeing Distribution',
    isEmergency: false,
    leadTime: 10,
    premiumPct: 0,
  },
  {
    id: 'pr-020',
    aircraftId: 'ac-007',
    tailNumber: 'N73807',
    category: 'Rotables',
    item: 'Nose wheel steering damper',
    quantity: 1,
    unitPrice: 18500,
    totalCost: 18500,
    status: 'Delivered',
    orderDate: '2026-03-15',
    expectedDelivery: '2026-03-22',
    actualDelivery: '2026-03-21',
    supplier: 'Heico Corp',
    isEmergency: false,
    leadTime: 5,
    premiumPct: 0,
  },
  {
    id: 'pr-021',
    aircraftId: 'ac-012',
    tailNumber: 'N38M04',
    category: 'Avionics LRUs',
    item: 'Inertial Reference Unit (IRU)',
    quantity: 1,
    unitPrice: 95000,
    totalCost: 95000,
    status: 'Ordered',
    orderDate: '2026-03-20',
    expectedDelivery: '2026-04-08',
    actualDelivery: null,
    supplier: 'Honeywell Aerospace',
    isEmergency: false,
    leadTime: 14,
    premiumPct: 0,
  },
  {
    id: 'pr-022',
    aircraftId: 'ac-003',
    tailNumber: 'N73803',
    category: 'Rotables',
    item: 'Flight Director Computer #1',
    quantity: 1,
    unitPrice: 72000,
    totalCost: 72000,
    status: 'Ordered',
    orderDate: '2026-03-18',
    expectedDelivery: '2026-04-05',
    actualDelivery: null,
    supplier: 'Honeywell Aerospace',
    isEmergency: false,
    leadTime: 14,
    premiumPct: 0,
  },
  {
    id: 'pr-023',
    aircraftId: 'ac-006',
    tailNumber: 'N73806',
    category: 'Consumables',
    item: 'Hydraulic fluid MIL-PRF-83282 (55 gal drum)',
    quantity: 2,
    unitPrice: 3200,
    totalCost: 6400,
    status: 'Delivered',
    orderDate: '2026-02-28',
    expectedDelivery: '2026-03-10',
    actualDelivery: '2026-03-08',
    supplier: 'Aviall Services',
    isEmergency: false,
    leadTime: 7,
    premiumPct: 0,
  },
  {
    id: 'pr-024',
    aircraftId: 'ac-020',
    tailNumber: 'N321A2',
    category: 'Expendables',
    item: 'Hydraulic pump inlet filter set',
    quantity: 4,
    unitPrice: 950,
    totalCost: 3800,
    status: 'Shipped',
    orderDate: '2026-03-12',
    expectedDelivery: '2026-03-25',
    actualDelivery: null,
    supplier: 'Airbus Spares',
    isEmergency: false,
    leadTime: 10,
    premiumPct: 0,
  },
  {
    id: 'pr-025',
    aircraftId: 'ac-025',
    tailNumber: 'N78903',
    category: 'Safety Equipment',
    item: 'Life raft overhaul service (2 units)',
    quantity: 2,
    unitPrice: 8500,
    totalCost: 17000,
    status: 'Pending Approval',
    orderDate: '2026-03-19',
    expectedDelivery: '2026-04-20',
    actualDelivery: null,
    supplier: 'Aviall Services',
    isEmergency: false,
    leadTime: 21,
    premiumPct: 0,
  },
  {
    id: 'pr-026',
    aircraftId: 'ac-011',
    tailNumber: 'N38M03',
    category: 'Consumables',
    item: 'Engine oil Mobil Jet Oil II (case of 24 qt)',
    quantity: 6,
    unitPrice: 350,
    totalCost: 2100,
    status: 'Delivered',
    orderDate: '2026-03-01',
    expectedDelivery: '2026-03-08',
    actualDelivery: '2026-03-07',
    supplier: 'Aviall Services',
    isEmergency: false,
    leadTime: 5,
    premiumPct: 0,
  },
  {
    id: 'pr-027',
    aircraftId: 'ac-019',
    tailNumber: 'N321A1',
    category: 'Rotables',
    item: 'APU igniter assembly',
    quantity: 2,
    unitPrice: 4200,
    totalCost: 8400,
    status: 'Delivered',
    orderDate: '2026-03-15',
    expectedDelivery: '2026-03-22',
    actualDelivery: '2026-03-21',
    supplier: 'Honeywell Aerospace',
    isEmergency: false,
    leadTime: 5,
    premiumPct: 0,
  },
  {
    id: 'pr-028',
    aircraftId: 'ac-022',
    tailNumber: 'N321A4',
    category: 'Expendables',
    item: 'Main tire assembly (set of 4)',
    quantity: 1,
    unitPrice: 6800,
    totalCost: 6800,
    status: 'Shipped',
    orderDate: '2026-03-10',
    expectedDelivery: '2026-03-24',
    actualDelivery: null,
    supplier: 'Heico Corp',
    isEmergency: false,
    leadTime: 10,
    premiumPct: 0,
  },
  {
    id: 'pr-029',
    aircraftId: 'ac-018',
    tailNumber: 'N320A6',
    category: 'Cabin Parts',
    item: 'Galley coffee maker replacement unit',
    quantity: 2,
    unitPrice: 3500,
    totalCost: 7000,
    status: 'Delivered',
    orderDate: '2026-03-02',
    expectedDelivery: '2026-03-12',
    actualDelivery: '2026-03-11',
    supplier: 'Airbus Spares',
    isEmergency: false,
    leadTime: 7,
    premiumPct: 0,
  },
  {
    id: 'pr-030',
    aircraftId: 'ac-008',
    tailNumber: 'N73808',
    category: 'Tooling',
    item: 'C-Check NDT inspection tooling rental',
    quantity: 1,
    unitPrice: 35000,
    totalCost: 35000,
    status: 'Delivered',
    orderDate: '2026-03-01',
    expectedDelivery: '2026-03-15',
    actualDelivery: '2026-03-14',
    supplier: 'Boeing Distribution',
    isEmergency: false,
    leadTime: 10,
    premiumPct: 0,
  },
  {
    id: 'pr-031',
    aircraftId: 'ac-010',
    tailNumber: 'N38M02',
    category: 'Rotables',
    item: 'Hydraulic pump assembly system A',
    quantity: 1,
    unitPrice: 52000,
    totalCost: 52000,
    status: 'Ordered',
    orderDate: '2026-03-21',
    expectedDelivery: '2026-04-04',
    actualDelivery: null,
    supplier: 'Boeing Distribution',
    isEmergency: false,
    leadTime: 10,
    premiumPct: 0,
  },
  {
    id: 'pr-032',
    aircraftId: 'ac-014',
    tailNumber: 'N320A2',
    category: 'Avionics LRUs',
    item: 'GPS receiver unit #2',
    quantity: 1,
    unitPrice: 45000,
    totalCost: 45000,
    status: 'Ordered',
    orderDate: '2026-03-20',
    expectedDelivery: '2026-04-08',
    actualDelivery: null,
    supplier: 'Honeywell Aerospace',
    isEmergency: false,
    leadTime: 14,
    premiumPct: 0,
  },
  {
    id: 'pr-033',
    aircraftId: 'ac-030',
    tailNumber: 'N35002',
    category: 'Safety Equipment',
    item: 'Cargo smoke detector zone 4 assembly',
    quantity: 1,
    unitPrice: 12000,
    totalCost: 12000,
    status: 'Shipped',
    orderDate: '2026-03-15',
    expectedDelivery: '2026-03-28',
    actualDelivery: null,
    supplier: 'Airbus Spares',
    isEmergency: false,
    leadTime: 10,
    premiumPct: 0,
  },
  {
    id: 'pr-034',
    aircraftId: 'ac-004',
    tailNumber: 'N73804',
    category: 'Rotables',
    item: 'Flight control computer channel B',
    quantity: 1,
    unitPrice: 88000,
    totalCost: 88000,
    status: 'Pending Approval',
    orderDate: '2026-03-22',
    expectedDelivery: '2026-04-12',
    actualDelivery: null,
    supplier: 'Honeywell Aerospace',
    isEmergency: false,
    leadTime: 14,
    premiumPct: 0,
  },
  {
    id: 'pr-035',
    aircraftId: 'ac-016',
    tailNumber: 'N320A4',
    category: 'Safety Equipment',
    item: 'ELT battery pack replacement',
    quantity: 1,
    unitPrice: 1800,
    totalCost: 1800,
    status: 'Shipped',
    orderDate: '2026-03-10',
    expectedDelivery: '2026-03-24',
    actualDelivery: null,
    supplier: 'Aviall Services',
    isEmergency: false,
    leadTime: 10,
    premiumPct: 0,
  },

  // ============================================================
  // EMERGENCY / AOG ORDERS (15) — premiumPct 50-300%
  // ============================================================
  {
    id: 'pr-041',
    aircraftId: 'ac-005',
    tailNumber: 'N73805',
    category: 'Engine Parts',
    item: 'CFM56-7B engine bleed valve assembly (AOG)',
    quantity: 1,
    unitPrice: 95000,
    totalCost: 285000,
    status: 'Emergency Order',
    orderDate: '2026-03-22',
    expectedDelivery: '2026-03-24',
    actualDelivery: null,
    supplier: 'GE Aviation Spares',
    isEmergency: true,
    leadTime: 2,
    premiumPct: 200,
  },
  {
    id: 'pr-042',
    aircraftId: 'ac-005',
    tailNumber: 'N73805',
    category: 'Consumables',
    item: 'Engine bleed system gasket and seal kit (AOG)',
    quantity: 1,
    unitPrice: 4500,
    totalCost: 9000,
    status: 'Emergency Order',
    orderDate: '2026-03-22',
    expectedDelivery: '2026-03-23',
    actualDelivery: null,
    supplier: 'GE Aviation Spares',
    isEmergency: true,
    leadTime: 1,
    premiumPct: 100,
  },
  {
    id: 'pr-043',
    aircraftId: 'ac-015',
    tailNumber: 'N320A3',
    category: 'Avionics LRUs',
    item: 'Flight Management Computer unit (AOG)',
    quantity: 1,
    unitPrice: 185000,
    totalCost: 462500,
    status: 'Emergency Order',
    orderDate: '2026-03-21',
    expectedDelivery: '2026-03-23',
    actualDelivery: null,
    supplier: 'Honeywell Aerospace',
    isEmergency: true,
    leadTime: 2,
    premiumPct: 150,
  },
  {
    id: 'pr-044',
    aircraftId: 'ac-015',
    tailNumber: 'N320A3',
    category: 'Consumables',
    item: 'FMC software load media and certification docs (AOG)',
    quantity: 1,
    unitPrice: 8000,
    totalCost: 12000,
    status: 'Delivered',
    orderDate: '2026-03-21',
    expectedDelivery: '2026-03-22',
    actualDelivery: '2026-03-22',
    supplier: 'Honeywell Aerospace',
    isEmergency: true,
    leadTime: 1,
    premiumPct: 50,
  },
  {
    id: 'pr-045',
    aircraftId: 'ac-013',
    tailNumber: 'N320A1',
    category: 'Engine Parts',
    item: 'LEAP-1A combustion chamber liner emergency stock',
    quantity: 1,
    unitPrice: 145000,
    totalCost: 362500,
    status: 'Emergency Order',
    orderDate: '2026-03-20',
    expectedDelivery: '2026-03-25',
    actualDelivery: null,
    supplier: 'Safran Parts',
    isEmergency: true,
    leadTime: 3,
    premiumPct: 150,
  },
  {
    id: 'pr-046',
    aircraftId: 'ac-017',
    tailNumber: 'N320A5',
    category: 'Engine Parts',
    item: 'LEAP-1A borescope inspection tooling (expedited)',
    quantity: 1,
    unitPrice: 25000,
    totalCost: 37500,
    status: 'Shipped',
    orderDate: '2026-03-19',
    expectedDelivery: '2026-03-24',
    actualDelivery: null,
    supplier: 'Safran Parts',
    isEmergency: true,
    leadTime: 3,
    premiumPct: 50,
  },
  {
    id: 'pr-047',
    aircraftId: 'ac-001',
    tailNumber: 'N73801',
    category: 'Rotables',
    item: 'MLG side brace assembly (expedited overhaul)',
    quantity: 2,
    unitPrice: 65000,
    totalCost: 195000,
    status: 'Emergency Order',
    orderDate: '2026-03-20',
    expectedDelivery: '2026-03-26',
    actualDelivery: null,
    supplier: 'Heico Corp',
    isEmergency: true,
    leadTime: 3,
    premiumPct: 50,
  },
  {
    id: 'pr-048',
    aircraftId: 'ac-015',
    tailNumber: 'N320A3',
    category: 'Engine Parts',
    item: 'LEAP-1A engine hot section repair kit',
    quantity: 1,
    unitPrice: 220000,
    totalCost: 550000,
    status: 'Ordered',
    orderDate: '2026-03-22',
    expectedDelivery: '2026-04-05',
    actualDelivery: null,
    supplier: 'Safran Parts',
    isEmergency: true,
    leadTime: 10,
    premiumPct: 150,
  },
  {
    id: 'pr-049',
    aircraftId: 'ac-008',
    tailNumber: 'N73808',
    category: 'Expendables',
    item: 'C-Check consumables kit (sealant, lockwire, cotter pins)',
    quantity: 1,
    unitPrice: 8500,
    totalCost: 12750,
    status: 'Delivered',
    orderDate: '2026-03-18',
    expectedDelivery: '2026-03-20',
    actualDelivery: '2026-03-19',
    supplier: 'Boeing Distribution',
    isEmergency: true,
    leadTime: 2,
    premiumPct: 50,
  },
  {
    id: 'pr-050',
    aircraftId: 'ac-028',
    tailNumber: 'N77702',
    category: 'Engine Parts',
    item: 'GE90-115B HPT nozzle guide vane set (expedited)',
    quantity: 1,
    unitPrice: 420000,
    totalCost: 840000,
    status: 'Shipped',
    orderDate: '2026-03-10',
    expectedDelivery: '2026-03-28',
    actualDelivery: null,
    supplier: 'GE Aviation Spares',
    isEmergency: true,
    leadTime: 14,
    premiumPct: 100,
  },
  {
    id: 'pr-051',
    aircraftId: 'ac-005',
    tailNumber: 'N73805',
    category: 'Tooling',
    item: 'Engine bleed system test rig rental (AOG)',
    quantity: 1,
    unitPrice: 15000,
    totalCost: 45000,
    status: 'Delivered',
    orderDate: '2026-03-22',
    expectedDelivery: '2026-03-23',
    actualDelivery: '2026-03-22',
    supplier: 'GE Aviation Spares',
    isEmergency: true,
    leadTime: 1,
    premiumPct: 200,
  },
  {
    id: 'pr-052',
    aircraftId: 'ac-015',
    tailNumber: 'N320A3',
    category: 'Avionics LRUs',
    item: 'Radio altimeter transceiver #2 (AOG loan)',
    quantity: 1,
    unitPrice: 42000,
    totalCost: 84000,
    status: 'Emergency Order',
    orderDate: '2026-03-22',
    expectedDelivery: '2026-03-24',
    actualDelivery: null,
    supplier: 'TransDigm Group',
    isEmergency: true,
    leadTime: 2,
    premiumPct: 100,
  },
  {
    id: 'pr-053',
    aircraftId: 'ac-027',
    tailNumber: 'N77701',
    category: 'Expendables',
    item: 'Trim air modulating valve (expedited)',
    quantity: 1,
    unitPrice: 8200,
    totalCost: 16400,
    status: 'Shipped',
    orderDate: '2026-03-22',
    expectedDelivery: '2026-03-25',
    actualDelivery: null,
    supplier: 'Boeing Distribution',
    isEmergency: true,
    leadTime: 3,
    premiumPct: 100,
  },
  {
    id: 'pr-054',
    aircraftId: 'ac-003',
    tailNumber: 'N73803',
    category: 'Rotables',
    item: 'Nose wheel steering position sensor (expedited)',
    quantity: 1,
    unitPrice: 5500,
    totalCost: 8250,
    status: 'Shipped',
    orderDate: '2026-03-21',
    expectedDelivery: '2026-03-24',
    actualDelivery: null,
    supplier: 'Heico Corp',
    isEmergency: true,
    leadTime: 2,
    premiumPct: 50,
  },
  {
    id: 'pr-055',
    aircraftId: 'ac-005',
    tailNumber: 'N73805',
    category: 'Consumables',
    item: 'AOG maintenance crew travel and accommodation',
    quantity: 1,
    unitPrice: 12000,
    totalCost: 12000,
    status: 'Delivered',
    orderDate: '2026-03-22',
    expectedDelivery: '2026-03-22',
    actualDelivery: '2026-03-22',
    supplier: 'Aviall Services',
    isEmergency: true,
    leadTime: 0,
    premiumPct: 0,
  },
];
